// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: avro/enums.proto

package org.cbzmq.game.enums;

/**
 * Protobuf enum {@code CharacterState}
 *
 * <pre>
 * 会生成多个对象文件，一个Message一个
 * </pre>
 */
public enum CharacterState
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>idle = 0;</code>
   *
   * <pre>
   *休息状态
   * </pre>
   */
  idle(0, 0),
  /**
   * <code>running = 1;</code>
   *
   * <pre>
   *处于奔跑中状态
   * </pre>
   */
  running(1, 1),
  /**
   * <code>jumping = 2;</code>
   *
   * <pre>
   *处于跳跃在空中的状态
   * </pre>
   */
  jumping(2, 2),
  /**
   * <code>death = 3;</code>
   *
   * <pre>
   *处于死亡的状态
   * </pre>
   */
  death(3, 3),
  /**
   * <code>falling = 4;</code>
   *
   * <pre>
   *处于下落的状态
   * </pre>
   */
  falling(4, 4),
  ;

  /**
   * <code>idle = 0;</code>
   *
   * <pre>
   *休息状态
   * </pre>
   */
  public static final int idle_VALUE = 0;
  /**
   * <code>running = 1;</code>
   *
   * <pre>
   *处于奔跑中状态
   * </pre>
   */
  public static final int running_VALUE = 1;
  /**
   * <code>jumping = 2;</code>
   *
   * <pre>
   *处于跳跃在空中的状态
   * </pre>
   */
  public static final int jumping_VALUE = 2;
  /**
   * <code>death = 3;</code>
   *
   * <pre>
   *处于死亡的状态
   * </pre>
   */
  public static final int death_VALUE = 3;
  /**
   * <code>falling = 4;</code>
   *
   * <pre>
   *处于下落的状态
   * </pre>
   */
  public static final int falling_VALUE = 4;


  public final int getNumber() { return value; }

  public static CharacterState valueOf(int value) {
    switch (value) {
      case 0: return idle;
      case 1: return running;
      case 2: return jumping;
      case 3: return death;
      case 4: return falling;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<CharacterState>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static com.google.protobuf.Internal.EnumLiteMap<CharacterState>
      internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<CharacterState>() {
          public CharacterState findValueByNumber(int number) {
            return CharacterState.valueOf(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(index);
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.cbzmq.game.enums.Enums.getDescriptor().getEnumTypes().get(0);
  }

  private static final CharacterState[] VALUES = values();

  public static CharacterState valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    return VALUES[desc.getIndex()];
  }

  private final int index;
  private final int value;

  private CharacterState(int index, int value) {
    this.index = index;
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:CharacterState)
}

