// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: avro/enums.proto

package org.cbzmq.game.enums;

/**
 * Protobuf enum {@code EnemyType}
 */
public enum EnemyType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>weak = 0;</code>
   */
  weak(0, 0),
  /**
   * <code>normal = 1;</code>
   */
  normal(1, 1),
  /**
   * <code>strong = 2;</code>
   */
  strong(2, 2),
  /**
   * <code>becomesBig = 3;</code>
   */
  becomesBig(3, 3),
  /**
   * <code>big = 4;</code>
   */
  big(4, 4),
  /**
   * <code>small = 5;</code>
   */
  small(5, 5),
  ;

  /**
   * <code>weak = 0;</code>
   */
  public static final int weak_VALUE = 0;
  /**
   * <code>normal = 1;</code>
   */
  public static final int normal_VALUE = 1;
  /**
   * <code>strong = 2;</code>
   */
  public static final int strong_VALUE = 2;
  /**
   * <code>becomesBig = 3;</code>
   */
  public static final int becomesBig_VALUE = 3;
  /**
   * <code>big = 4;</code>
   */
  public static final int big_VALUE = 4;
  /**
   * <code>small = 5;</code>
   */
  public static final int small_VALUE = 5;


  public final int getNumber() { return value; }

  public static EnemyType valueOf(int value) {
    switch (value) {
      case 0: return weak;
      case 1: return normal;
      case 2: return strong;
      case 3: return becomesBig;
      case 4: return big;
      case 5: return small;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<EnemyType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static com.google.protobuf.Internal.EnumLiteMap<EnemyType>
      internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<EnemyType>() {
          public EnemyType findValueByNumber(int number) {
            return EnemyType.valueOf(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(index);
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.cbzmq.game.enums.Enums.getDescriptor().getEnumTypes().get(2);
  }

  private static final EnemyType[] VALUES = values();

  public static EnemyType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    return VALUES[desc.getIndex()];
  }

  private final int index;
  private final int value;

  private EnemyType(int index, int value) {
    this.index = index;
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:EnemyType)
}

