// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: avro/enums.proto

package org.cbzmq.game.enums;

public final class Enums {
  private Enums() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020avro/enums.proto*B\n\016CharacterState\022\010\n\004" +
      "idle\020\000\022\007\n\003run\020\001\022\010\n\004jump\020\002\022\t\n\005death\020\003\022\010\n\004" +
      "fall\020\004*?\n\rCharacterType\022\n\n\006player\020\000\022\t\n\005e" +
      "nemy\020\001\022\n\n\006bullet\020\002\022\013\n\007unknown\020\003*Q\n\tEnemy" +
      "Type\022\010\n\004weak\020\000\022\n\n\006normal\020\001\022\n\n\006strong\020\002\022\016" +
      "\n\nbecomesBig\020\003\022\007\n\003big\020\004\022\t\n\005small\020\005*\177\n\tMs" +
      "gHeader\022\030\n\024SYNC_CHARACTERS_INFO\020\000\022\031\n\025SYN" +
      "C_CHARACTERS_EVENT\020\001\022\024\n\020SYNC_GAME_STATUS" +
      "\020\003\022\014\n\010REGISTER\020\004\022\010\n\004QUIT\020\005\022\017\n\013GAME_ACTIO" +
      "N\020\006**\n\nGameAction\022\010\n\004JUMP\020\000\022\007\n\003RUN\020\001\022\t\n\005",
      "SHOOT\020\002*Z\n\nGameStatus\022\r\n\tNOT_START\020\000\022\013\n\007" +
      "LOADING\020\001\022\t\n\005READY\020\002\022\013\n\007RUNNING\020\003\022\r\n\tGAM" +
      "E_OVER\020\004\022\t\n\005PAUSE\020\005*#\n\004Code\022\007\n\002OK\020\310\001\022\022\n\r" +
      "SERVER_FAILED\020\364\003B\030\n\024org.cbzmq.game.enums" +
      "P\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
