// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: avro/enums.proto

package org.cbzmq.game.enums;

/**
 * Protobuf enum {@code GameStatus}
 *
 * <pre>
 *游戏状态
 * </pre>
 */
public enum GameStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>NOT_START = 0;</code>
   *
   * <pre>
   * 未开始
   * </pre>
   */
  NOT_START(0, 0),
  /**
   * <code>LOADING = 1;</code>
   *
   * <pre>
   * 加载状态
   * </pre>
   */
  LOADING(1, 1),
  /**
   * <code>READY = 2;</code>
   *
   * <pre>
   * 准备
   * </pre>
   */
  READY(2, 2),
  /**
   * <code>RUNNING = 3;</code>
   *
   * <pre>
   *已开始
   * </pre>
   */
  RUNNING(3, 3),
  /**
   * <code>GAME_OVER = 4;</code>
   *
   * <pre>
   *结束
   * </pre>
   */
  GAME_OVER(4, 4),
  /**
   * <code>PAUSE = 5;</code>
   *
   * <pre>
   *暂停状态
   * </pre>
   */
  PAUSE(5, 5),
  ;

  /**
   * <code>NOT_START = 0;</code>
   *
   * <pre>
   * 未开始
   * </pre>
   */
  public static final int NOT_START_VALUE = 0;
  /**
   * <code>LOADING = 1;</code>
   *
   * <pre>
   * 加载状态
   * </pre>
   */
  public static final int LOADING_VALUE = 1;
  /**
   * <code>READY = 2;</code>
   *
   * <pre>
   * 准备
   * </pre>
   */
  public static final int READY_VALUE = 2;
  /**
   * <code>RUNNING = 3;</code>
   *
   * <pre>
   *已开始
   * </pre>
   */
  public static final int RUNNING_VALUE = 3;
  /**
   * <code>GAME_OVER = 4;</code>
   *
   * <pre>
   *结束
   * </pre>
   */
  public static final int GAME_OVER_VALUE = 4;
  /**
   * <code>PAUSE = 5;</code>
   *
   * <pre>
   *暂停状态
   * </pre>
   */
  public static final int PAUSE_VALUE = 5;


  public final int getNumber() { return value; }

  public static GameStatus valueOf(int value) {
    switch (value) {
      case 0: return NOT_START;
      case 1: return LOADING;
      case 2: return READY;
      case 3: return RUNNING;
      case 4: return GAME_OVER;
      case 5: return PAUSE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<GameStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static com.google.protobuf.Internal.EnumLiteMap<GameStatus>
      internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<GameStatus>() {
          public GameStatus findValueByNumber(int number) {
            return GameStatus.valueOf(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(index);
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.cbzmq.game.enums.Enums.getDescriptor().getEnumTypes().get(5);
  }

  private static final GameStatus[] VALUES = values();

  public static GameStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    return VALUES[desc.getIndex()];
  }

  private final int index;
  private final int value;

  private GameStatus(int index, int value) {
    this.index = index;
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:GameStatus)
}

