// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: avro/enums.proto

package org.cbzmq.game.enums;

/**
 * Protobuf enum {@code GameAction}
 */
public enum GameAction
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>JUMP = 0;</code>
   */
  JUMP(0, 0),
  /**
   * <code>RUN = 1;</code>
   */
  RUN(1, 1),
  /**
   * <code>SHOOT = 2;</code>
   */
  SHOOT(2, 2),
  ;

  /**
   * <code>JUMP = 0;</code>
   */
  public static final int JUMP_VALUE = 0;
  /**
   * <code>RUN = 1;</code>
   */
  public static final int RUN_VALUE = 1;
  /**
   * <code>SHOOT = 2;</code>
   */
  public static final int SHOOT_VALUE = 2;


  public final int getNumber() { return value; }

  public static GameAction valueOf(int value) {
    switch (value) {
      case 0: return JUMP;
      case 1: return RUN;
      case 2: return SHOOT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<GameAction>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static com.google.protobuf.Internal.EnumLiteMap<GameAction>
      internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<GameAction>() {
          public GameAction findValueByNumber(int number) {
            return GameAction.valueOf(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(index);
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.cbzmq.game.enums.Enums.getDescriptor().getEnumTypes().get(4);
  }

  private static final GameAction[] VALUES = values();

  public static GameAction valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    return VALUES[desc.getIndex()];
  }

  private final int index;
  private final int value;

  private GameAction(int index, int value) {
    this.index = index;
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:GameAction)
}

