// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: avro/enums.proto

package org.cbzmq.game.enums;

/**
 * Protobuf enum {@code MsgHeader}
 *
 * <pre>
 **服务端的请求头*
 * </pre>
 */
public enum MsgHeader
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>SYNC_CHARACTERS_INFO = 0;</code>
   *
   * <pre>
   *同步所有角色的信息给客户端
   * </pre>
   */
  SYNC_CHARACTERS_INFO(0, 0),
  /**
   * <code>SYNC_CHARACTERS_EVENT = 1;</code>
   *
   * <pre>
   *同步角色的事件给客户端
   * </pre>
   */
  SYNC_CHARACTERS_EVENT(1, 1),
  /**
   * <code>SYNC_GAME_STATUS = 3;</code>
   *
   * <pre>
   *同步角色的事件给客户端
   * </pre>
   */
  SYNC_GAME_STATUS(2, 3),
  /**
   * <code>REGISTER = 4;</code>
   *
   * <pre>
   *客户端
   * </pre>
   */
  REGISTER(3, 4),
  /**
   * <code>QUIT = 5;</code>
   */
  QUIT(4, 5),
  /**
   * <code>GAME_ACTION = 6;</code>
   *
   * <pre>
   *游戏操作
   * </pre>
   */
  GAME_ACTION(5, 6),
  ;

  /**
   * <code>SYNC_CHARACTERS_INFO = 0;</code>
   *
   * <pre>
   *同步所有角色的信息给客户端
   * </pre>
   */
  public static final int SYNC_CHARACTERS_INFO_VALUE = 0;
  /**
   * <code>SYNC_CHARACTERS_EVENT = 1;</code>
   *
   * <pre>
   *同步角色的事件给客户端
   * </pre>
   */
  public static final int SYNC_CHARACTERS_EVENT_VALUE = 1;
  /**
   * <code>SYNC_GAME_STATUS = 3;</code>
   *
   * <pre>
   *同步角色的事件给客户端
   * </pre>
   */
  public static final int SYNC_GAME_STATUS_VALUE = 3;
  /**
   * <code>REGISTER = 4;</code>
   *
   * <pre>
   *客户端
   * </pre>
   */
  public static final int REGISTER_VALUE = 4;
  /**
   * <code>QUIT = 5;</code>
   */
  public static final int QUIT_VALUE = 5;
  /**
   * <code>GAME_ACTION = 6;</code>
   *
   * <pre>
   *游戏操作
   * </pre>
   */
  public static final int GAME_ACTION_VALUE = 6;


  public final int getNumber() { return value; }

  public static MsgHeader valueOf(int value) {
    switch (value) {
      case 0: return SYNC_CHARACTERS_INFO;
      case 1: return SYNC_CHARACTERS_EVENT;
      case 3: return SYNC_GAME_STATUS;
      case 4: return REGISTER;
      case 5: return QUIT;
      case 6: return GAME_ACTION;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MsgHeader>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static com.google.protobuf.Internal.EnumLiteMap<MsgHeader>
      internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<MsgHeader>() {
          public MsgHeader findValueByNumber(int number) {
            return MsgHeader.valueOf(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(index);
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.cbzmq.game.enums.Enums.getDescriptor().getEnumTypes().get(3);
  }

  private static final MsgHeader[] VALUES = values();

  public static MsgHeader valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    return VALUES[desc.getIndex()];
  }

  private final int index;
  private final int value;

  private MsgHeader(int index, int value) {
    this.index = index;
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:MsgHeader)
}

