// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enums.proto

package awt.proto.enums;

public final class Enums {
  private Enums() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013enums.proto*\245\001\n\tMsgAction\022\t\n\005LOGIN\020\001\022\n" +
      "\n\006LOGOUT\020\002\022\t\n\005HEART\020\003\022\024\n\020SYNC_GAME_STATU" +
      "S\020\004\022\r\n\tGAME_JOIN\020\005\022\017\n\013GAME_ACTION\020\006\022\026\n\022B" +
      "ROADCAST_GAME_MAP\020\007\022\025\n\021BROADCAST_COMMAND" +
      "\020\010\022\021\n\rSYNC_GAME_MAP\020\t*\221\001\n\nUserAction\022\014\n\010" +
      "REGISTER\020\000\022\016\n\nSTART_PLAY\020\001\022\013\n\007OFFLINE\020\002\022" +
      "\016\n\nUSER_LOGIN\020\003\022\021\n\rGET_GAME_STAT\020\004\022\024\n\020LO" +
      "CK_PERSPECTIVE\020\005\022\026\n\022UNLOCK_PERSPECTIVE\020\006" +
      "\022\007\n\003MAP\020\007*Z\n\nGameStatus\022\r\n\tNOT_START\020\000\022\013" +
      "\n\007LOADING\020\001\022\t\n\005READY\020\002\022\013\n\007RUNNING\020\003\022\r\n\tG",
      "AME_OVER\020\004\022\t\n\005PAUSE\020\005*:\n\010GameRole\022\n\n\006PLA" +
      "YER\020\000\022\007\n\003NPC\020\001\022\t\n\005SCENE\020\003\022\016\n\nDERIVATIVE\020" +
      "\004*F\n\006Status\022\n\n\006ACCEPT\020\001\022\013\n\007SUCCESS\020\002\022\n\n\006" +
      "FAILED\020\003\022\r\n\tINTERRUPT\020\004\022\010\n\004WAIT\020\005*#\n\004Cod" +
      "e\022\007\n\002OK\020\310\001\022\022\n\rSERVER_FAILED\020\364\003*H\n\013Elemen" +
      "tType\022\010\n\004TANK\020\000\022\n\n\006BULLET\020\001\022\010\n\004WALL\020\002\022\t\n" +
      "\005RIVER\020\003\022\016\n\nGRASS_LAND\020\004*/\n\006Direct\022\006\n\002UP" +
      "\020\000\022\010\n\004DOWN\020\001\022\t\n\005RIGHT\020\002\022\010\n\004LEFT\020\003*B\n\rEle" +
      "mentAction\022\010\n\004DEAD\020\001\022\010\n\004MOVE\020\002\022\010\n\004LIVE\020\003" +
      "\022\t\n\005BLOOD\020\004\022\010\n\004STEP\020\005*\220\001\n\nTankAction\022\010\n\004",
      "FIRE\020\001\022\010\n\004STOP\020\002\022\r\n\tTURN_LEFT\020\004\022\016\n\nTURN_" +
      "RIGHT\020\005\022\013\n\007TURN_UP\020\006\022\r\n\tTURN_DOWN\020\007\022\014\n\010S" +
      "TAND_BY\020\010\022\026\n\022AMMUNITION_LOADING\020\t\022\r\n\tTAN" +
      "K_MOVE\020\n*\201\001\n\013CommandType\022\032\n\026ELEMENT_UPDA" +
      "TE_COMMAND\020\000\022\024\n\020REDIRECT_COMMAND\020\001\022\020\n\014TA" +
      "NK_COMMAND\020\002\022\027\n\023USER_ACTION_COMMAND\020\003\022\025\n" +
      "\021TANK_FIRE_COMMAND\020\004B\023\n\017awt.proto.enumsP" +
      "\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
