// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enums.proto

package awt.proto.enums;

/**
 * Protobuf enum {@code MsgAction}
 */
public enum MsgAction
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>LOGIN = 1;</code>
   *
   * <pre>
   *客户端登陆
   * </pre>
   */
  LOGIN(0, 1),
  /**
   * <code>LOGOUT = 2;</code>
   *
   * <pre>
   *客户端退出
   * </pre>
   */
  LOGOUT(1, 2),
  /**
   * <code>HEART = 3;</code>
   *
   * <pre>
   *心跳消息
   * </pre>
   */
  HEART(2, 3),
  /**
   * <code>SYNC_GAME_STATUS = 4;</code>
   *
   * <pre>
   *同步游戏加载进度
   * </pre>
   */
  SYNC_GAME_STATUS(3, 4),
  /**
   * <code>GAME_JOIN = 5;</code>
   *
   * <pre>
   *客户端加入
   * </pre>
   */
  GAME_JOIN(4, 5),
  /**
   * <code>GAME_ACTION = 6;</code>
   *
   * <pre>
   *客户端游戏操作
   * </pre>
   */
  GAME_ACTION(5, 6),
  /**
   * <code>BROADCAST_GAME_MAP = 7;</code>
   *
   * <pre>
   *同步游戏地图信息
   * </pre>
   */
  BROADCAST_GAME_MAP(6, 7),
  /**
   * <code>BROADCAST_COMMAND = 8;</code>
   *
   * <pre>
   *同步游戏地图信息
   * </pre>
   */
  BROADCAST_COMMAND(7, 8),
  /**
   * <code>SYNC_GAME_MAP = 9;</code>
   *
   * <pre>
   *同步游戏地图
   * </pre>
   */
  SYNC_GAME_MAP(8, 9),
  ;

  /**
   * <code>LOGIN = 1;</code>
   *
   * <pre>
   *客户端登陆
   * </pre>
   */
  public static final int LOGIN_VALUE = 1;
  /**
   * <code>LOGOUT = 2;</code>
   *
   * <pre>
   *客户端退出
   * </pre>
   */
  public static final int LOGOUT_VALUE = 2;
  /**
   * <code>HEART = 3;</code>
   *
   * <pre>
   *心跳消息
   * </pre>
   */
  public static final int HEART_VALUE = 3;
  /**
   * <code>SYNC_GAME_STATUS = 4;</code>
   *
   * <pre>
   *同步游戏加载进度
   * </pre>
   */
  public static final int SYNC_GAME_STATUS_VALUE = 4;
  /**
   * <code>GAME_JOIN = 5;</code>
   *
   * <pre>
   *客户端加入
   * </pre>
   */
  public static final int GAME_JOIN_VALUE = 5;
  /**
   * <code>GAME_ACTION = 6;</code>
   *
   * <pre>
   *客户端游戏操作
   * </pre>
   */
  public static final int GAME_ACTION_VALUE = 6;
  /**
   * <code>BROADCAST_GAME_MAP = 7;</code>
   *
   * <pre>
   *同步游戏地图信息
   * </pre>
   */
  public static final int BROADCAST_GAME_MAP_VALUE = 7;
  /**
   * <code>BROADCAST_COMMAND = 8;</code>
   *
   * <pre>
   *同步游戏地图信息
   * </pre>
   */
  public static final int BROADCAST_COMMAND_VALUE = 8;
  /**
   * <code>SYNC_GAME_MAP = 9;</code>
   *
   * <pre>
   *同步游戏地图
   * </pre>
   */
  public static final int SYNC_GAME_MAP_VALUE = 9;


  public final int getNumber() { return value; }

  public static MsgAction valueOf(int value) {
    switch (value) {
      case 1: return LOGIN;
      case 2: return LOGOUT;
      case 3: return HEART;
      case 4: return SYNC_GAME_STATUS;
      case 5: return GAME_JOIN;
      case 6: return GAME_ACTION;
      case 7: return BROADCAST_GAME_MAP;
      case 8: return BROADCAST_COMMAND;
      case 9: return SYNC_GAME_MAP;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MsgAction>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static com.google.protobuf.Internal.EnumLiteMap<MsgAction>
      internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<MsgAction>() {
          public MsgAction findValueByNumber(int number) {
            return MsgAction.valueOf(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(index);
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return awt.proto.enums.Enums.getDescriptor().getEnumTypes().get(0);
  }

  private static final MsgAction[] VALUES = values();

  public static MsgAction valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    return VALUES[desc.getIndex()];
  }

  private final int index;
  private final int value;

  private MsgAction(int index, int value) {
    this.index = index;
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:MsgAction)
}

