// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enums.proto

package awt.proto.enums;

/**
 * Protobuf enum {@code TankAction}
 *
 * <pre>
 *坦克动作
 * </pre>
 */
public enum TankAction
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>FIRE = 1;</code>
   *
   * <pre>
   *开火
   * </pre>
   */
  FIRE(0, 1),
  /**
   * <code>STOP = 2;</code>
   *
   * <pre>
   *停止
   * </pre>
   */
  STOP(1, 2),
  /**
   * <code>TURN_LEFT = 4;</code>
   *
   * <pre>
   * 转左
   * </pre>
   */
  TURN_LEFT(2, 4),
  /**
   * <code>TURN_RIGHT = 5;</code>
   *
   * <pre>
   *转右边
   * </pre>
   */
  TURN_RIGHT(3, 5),
  /**
   * <code>TURN_UP = 6;</code>
   *
   * <pre>
   *转上
   * </pre>
   */
  TURN_UP(4, 6),
  /**
   * <code>TURN_DOWN = 7;</code>
   *
   * <pre>
   *转下
   * </pre>
   */
  TURN_DOWN(5, 7),
  /**
   * <code>STAND_BY = 8;</code>
   *
   * <pre>
   *等待
   * </pre>
   */
  STAND_BY(6, 8),
  /**
   * <code>AMMUNITION_LOADING = 9;</code>
   *
   * <pre>
   *装弹
   * </pre>
   */
  AMMUNITION_LOADING(7, 9),
  /**
   * <code>TANK_MOVE = 10;</code>
   *
   * <pre>
   *tank移动
   * </pre>
   */
  TANK_MOVE(8, 10),
  ;

  /**
   * <code>FIRE = 1;</code>
   *
   * <pre>
   *开火
   * </pre>
   */
  public static final int FIRE_VALUE = 1;
  /**
   * <code>STOP = 2;</code>
   *
   * <pre>
   *停止
   * </pre>
   */
  public static final int STOP_VALUE = 2;
  /**
   * <code>TURN_LEFT = 4;</code>
   *
   * <pre>
   * 转左
   * </pre>
   */
  public static final int TURN_LEFT_VALUE = 4;
  /**
   * <code>TURN_RIGHT = 5;</code>
   *
   * <pre>
   *转右边
   * </pre>
   */
  public static final int TURN_RIGHT_VALUE = 5;
  /**
   * <code>TURN_UP = 6;</code>
   *
   * <pre>
   *转上
   * </pre>
   */
  public static final int TURN_UP_VALUE = 6;
  /**
   * <code>TURN_DOWN = 7;</code>
   *
   * <pre>
   *转下
   * </pre>
   */
  public static final int TURN_DOWN_VALUE = 7;
  /**
   * <code>STAND_BY = 8;</code>
   *
   * <pre>
   *等待
   * </pre>
   */
  public static final int STAND_BY_VALUE = 8;
  /**
   * <code>AMMUNITION_LOADING = 9;</code>
   *
   * <pre>
   *装弹
   * </pre>
   */
  public static final int AMMUNITION_LOADING_VALUE = 9;
  /**
   * <code>TANK_MOVE = 10;</code>
   *
   * <pre>
   *tank移动
   * </pre>
   */
  public static final int TANK_MOVE_VALUE = 10;


  public final int getNumber() { return value; }

  public static TankAction valueOf(int value) {
    switch (value) {
      case 1: return FIRE;
      case 2: return STOP;
      case 4: return TURN_LEFT;
      case 5: return TURN_RIGHT;
      case 6: return TURN_UP;
      case 7: return TURN_DOWN;
      case 8: return STAND_BY;
      case 9: return AMMUNITION_LOADING;
      case 10: return TANK_MOVE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<TankAction>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static com.google.protobuf.Internal.EnumLiteMap<TankAction>
      internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<TankAction>() {
          public TankAction findValueByNumber(int number) {
            return TankAction.valueOf(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(index);
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return awt.proto.enums.Enums.getDescriptor().getEnumTypes().get(9);
  }

  private static final TankAction[] VALUES = values();

  public static TankAction valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    return VALUES[desc.getIndex()];
  }

  private final int index;
  private final int value;

  private TankAction(int index, int value) {
    this.index = index;
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:TankAction)
}

