// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enums.proto

package awt.proto.enums;

/**
 * Protobuf enum {@code UserAction}
 *
 * <pre>
 *用户动作
 * </pre>
 */
public enum UserAction
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>REGISTER = 0;</code>
   *
   * <pre>
   *客户端
   * </pre>
   */
  REGISTER(0, 0),
  /**
   * <code>START_PLAY = 1;</code>
   *
   * <pre>
   *开始游戏
   * </pre>
   */
  START_PLAY(1, 1),
  /**
   * <code>OFFLINE = 2;</code>
   *
   * <pre>
   *掉线
   * </pre>
   */
  OFFLINE(2, 2),
  /**
   * <code>USER_LOGIN = 3;</code>
   *
   * <pre>
   *登录
   * </pre>
   */
  USER_LOGIN(3, 3),
  /**
   * <code>GET_GAME_STAT = 4;</code>
   *
   * <pre>
   *获取游戏状态
   * </pre>
   */
  GET_GAME_STAT(4, 4),
  /**
   * <code>LOCK_PERSPECTIVE = 5;</code>
   *
   * <pre>
   *锁定视角
   * </pre>
   */
  LOCK_PERSPECTIVE(5, 5),
  /**
   * <code>UNLOCK_PERSPECTIVE = 6;</code>
   *
   * <pre>
   *解锁视角
   * </pre>
   */
  UNLOCK_PERSPECTIVE(6, 6),
  /**
   * <code>MAP = 7;</code>
   *
   * <pre>
   *地图
   * </pre>
   */
  MAP(7, 7),
  ;

  /**
   * <code>REGISTER = 0;</code>
   *
   * <pre>
   *客户端
   * </pre>
   */
  public static final int REGISTER_VALUE = 0;
  /**
   * <code>START_PLAY = 1;</code>
   *
   * <pre>
   *开始游戏
   * </pre>
   */
  public static final int START_PLAY_VALUE = 1;
  /**
   * <code>OFFLINE = 2;</code>
   *
   * <pre>
   *掉线
   * </pre>
   */
  public static final int OFFLINE_VALUE = 2;
  /**
   * <code>USER_LOGIN = 3;</code>
   *
   * <pre>
   *登录
   * </pre>
   */
  public static final int USER_LOGIN_VALUE = 3;
  /**
   * <code>GET_GAME_STAT = 4;</code>
   *
   * <pre>
   *获取游戏状态
   * </pre>
   */
  public static final int GET_GAME_STAT_VALUE = 4;
  /**
   * <code>LOCK_PERSPECTIVE = 5;</code>
   *
   * <pre>
   *锁定视角
   * </pre>
   */
  public static final int LOCK_PERSPECTIVE_VALUE = 5;
  /**
   * <code>UNLOCK_PERSPECTIVE = 6;</code>
   *
   * <pre>
   *解锁视角
   * </pre>
   */
  public static final int UNLOCK_PERSPECTIVE_VALUE = 6;
  /**
   * <code>MAP = 7;</code>
   *
   * <pre>
   *地图
   * </pre>
   */
  public static final int MAP_VALUE = 7;


  public final int getNumber() { return value; }

  public static UserAction valueOf(int value) {
    switch (value) {
      case 0: return REGISTER;
      case 1: return START_PLAY;
      case 2: return OFFLINE;
      case 3: return USER_LOGIN;
      case 4: return GET_GAME_STAT;
      case 5: return LOCK_PERSPECTIVE;
      case 6: return UNLOCK_PERSPECTIVE;
      case 7: return MAP;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<UserAction>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static com.google.protobuf.Internal.EnumLiteMap<UserAction>
      internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<UserAction>() {
          public UserAction findValueByNumber(int number) {
            return UserAction.valueOf(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(index);
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return awt.proto.enums.Enums.getDescriptor().getEnumTypes().get(1);
  }

  private static final UserAction[] VALUES = values();

  public static UserAction valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    return VALUES[desc.getIndex()];
  }

  private final int index;
  private final int value;

  private UserAction(int index, int value) {
    this.index = index;
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:UserAction)
}

