// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: avro/enums.proto

package org.cbzmq.game.proto;

import com.baidu.bjf.remoting.protobuf.annotation.ProtobufClass;
import lombok.AccessLevel;
import lombok.experimental.FieldDefaults;

@ProtobufClass
@FieldDefaults(level = AccessLevel.PUBLIC)
public enum CharacterState {
  /**
   * <code>idle = 0;</code>
   *
   * <pre>
   *休息状态
   * </pre>
   */
  idle,
  /**
   * <code>running = 1;</code>
   *
   * <pre>
   *处于奔跑中状态
   * </pre>
   */
  running,
  /**
   * <code>jumping = 2;</code>
   *
   * <pre>
   *处于跳跃在空中的状态
   * </pre>
   */
  jumping,
  /**
   * <code>death = 3;</code>
   *
   * <pre>
   *处于死亡的状态
   * </pre>
   */
  death,
  /**
   * <code>falling = 4;</code>
   *
   * <pre>
   *处于下落的状态
   * </pre>
   */
  falling,

}

