// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: avro/enums.proto

package org.cbzmq.game.proto;

import com.baidu.bjf.remoting.protobuf.annotation.ProtobufClass;
import lombok.AccessLevel;
import lombok.experimental.FieldDefaults;

@ProtobufClass
@FieldDefaults(level = AccessLevel.PUBLIC)
public enum CharacterType
{
  /**
   * <code>player = 0;</code>
   */
  player,
  /**
   * <code>enemy = 1;</code>
   */
  enemy,
  /**
   * <code>bullet = 2;</code>
   */
  bullet,
  /**
   * <code>unknown = 3;</code>
   */
  unknown,
  ;

}

