// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: avro/enums.proto

package org.cbzmq.game.proto;

import com.baidu.bjf.remoting.protobuf.annotation.ProtobufClass;
import lombok.AccessLevel;
import lombok.experimental.FieldDefaults;

@ProtobufClass
@FieldDefaults(level = AccessLevel.PUBLIC)
public enum EnemyType
{
  /**
   * <code>weak = 0;</code>
   */
  weak,
  /**
   * <code>normal = 1;</code>
   */
  normal,
  /**
   * <code>strong = 2;</code>
   */
  strong,
  /**
   * <code>becomesBig = 3;</code>
   */
  becomesBig,
  /**
   * <code>big = 4;</code>
   */
  big,
  /**
   * <code>small = 5;</code>
   */
  small,
  ;

}

