// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: avro/enums.proto

package org.cbzmq.game.proto;

import com.baidu.bjf.remoting.protobuf.annotation.ProtobufClass;
import lombok.AccessLevel;
import lombok.experimental.FieldDefaults;

@ProtobufClass
@FieldDefaults(level = AccessLevel.PUBLIC)

public enum GameAction
 {
  /**
   * <code>JUMP = 0;</code>
   */
  JUMP,
  /**
   * <code>RUN = 1;</code>
   */
  RUN,
  /**
   * <code>SHOOT = 2;</code>
   */
  SHOOT,
  
}

