// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: avro/msg.proto

package org.cbzmq.game.proto;

public final class MsgProto {
  private MsgProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 id = 1;
    /**
     * <code>required int64 id = 1;</code>
     *
     * <pre>
     *自身属性
     * </pre>
     */
    boolean hasId();
    /**
     * <code>required int64 id = 1;</code>
     *
     * <pre>
     *自身属性
     * </pre>
     */
    long getId();

    // required .MsgHeader header = 2;
    /**
     * <code>required .MsgHeader header = 2;</code>
     */
    boolean hasHeader();
    /**
     * <code>required .MsgHeader header = 2;</code>
     */
    org.cbzmq.game.enums.MsgHeader getHeader();

    // required int64 timeStamp = 3;
    /**
     * <code>required int64 timeStamp = 3;</code>
     */
    boolean hasTimeStamp();
    /**
     * <code>required int64 timeStamp = 3;</code>
     */
    long getTimeStamp();

    // optional .Code code = 4;
    /**
     * <code>optional .Code code = 4;</code>
     */
    boolean hasCode();
    /**
     * <code>optional .Code code = 4;</code>
     */
    org.cbzmq.game.enums.Code getCode();

    // repeated .Character characterData = 5;
    /**
     * <code>repeated .Character characterData = 5;</code>
     */
    java.util.List<org.cbzmq.game.proto.CharacterProto.Character> 
        getCharacterDataList();
    /**
     * <code>repeated .Character characterData = 5;</code>
     */
    org.cbzmq.game.proto.CharacterProto.Character getCharacterData(int index);
    /**
     * <code>repeated .Character characterData = 5;</code>
     */
    int getCharacterDataCount();
    /**
     * <code>repeated .Character characterData = 5;</code>
     */
    java.util.List<? extends org.cbzmq.game.proto.CharacterProto.CharacterOrBuilder> 
        getCharacterDataOrBuilderList();
    /**
     * <code>repeated .Character characterData = 5;</code>
     */
    org.cbzmq.game.proto.CharacterProto.CharacterOrBuilder getCharacterDataOrBuilder(
        int index);

    // repeated .Event events = 6;
    /**
     * <code>repeated .Event events = 6;</code>
     */
    java.util.List<org.cbzmq.game.proto.MsgProto.Event> 
        getEventsList();
    /**
     * <code>repeated .Event events = 6;</code>
     */
    org.cbzmq.game.proto.MsgProto.Event getEvents(int index);
    /**
     * <code>repeated .Event events = 6;</code>
     */
    int getEventsCount();
    /**
     * <code>repeated .Event events = 6;</code>
     */
    java.util.List<? extends org.cbzmq.game.proto.MsgProto.EventOrBuilder> 
        getEventsOrBuilderList();
    /**
     * <code>repeated .Event events = 6;</code>
     */
    org.cbzmq.game.proto.MsgProto.EventOrBuilder getEventsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Msg}
   */
  public static final class Msg extends
      com.google.protobuf.GeneratedMessage
      implements MsgOrBuilder {
    // Use Msg.newBuilder() to construct.
    private Msg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Msg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Msg defaultInstance;
    public static Msg getDefaultInstance() {
      return defaultInstance;
    }

    public Msg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Msg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              org.cbzmq.game.enums.MsgHeader value = org.cbzmq.game.enums.MsgHeader.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                header_ = value;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              timeStamp_ = input.readInt64();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              org.cbzmq.game.enums.Code value = org.cbzmq.game.enums.Code.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                code_ = value;
              }
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                characterData_ = new java.util.ArrayList<org.cbzmq.game.proto.CharacterProto.Character>();
                mutable_bitField0_ |= 0x00000010;
              }
              characterData_.add(input.readMessage(org.cbzmq.game.proto.CharacterProto.Character.PARSER, extensionRegistry));
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                events_ = new java.util.ArrayList<org.cbzmq.game.proto.MsgProto.Event>();
                mutable_bitField0_ |= 0x00000020;
              }
              events_.add(input.readMessage(org.cbzmq.game.proto.MsgProto.Event.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          characterData_ = java.util.Collections.unmodifiableList(characterData_);
        }
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          events_ = java.util.Collections.unmodifiableList(events_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.cbzmq.game.proto.MsgProto.internal_static_Msg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.cbzmq.game.proto.MsgProto.internal_static_Msg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.cbzmq.game.proto.MsgProto.Msg.class, org.cbzmq.game.proto.MsgProto.Msg.Builder.class);
    }

    public static com.google.protobuf.Parser<Msg> PARSER =
        new com.google.protobuf.AbstractParser<Msg>() {
      public Msg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Msg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Msg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>required int64 id = 1;</code>
     *
     * <pre>
     *自身属性
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 id = 1;</code>
     *
     * <pre>
     *自身属性
     * </pre>
     */
    public long getId() {
      return id_;
    }

    // required .MsgHeader header = 2;
    public static final int HEADER_FIELD_NUMBER = 2;
    private org.cbzmq.game.enums.MsgHeader header_;
    /**
     * <code>required .MsgHeader header = 2;</code>
     */
    public boolean hasHeader() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .MsgHeader header = 2;</code>
     */
    public org.cbzmq.game.enums.MsgHeader getHeader() {
      return header_;
    }

    // required int64 timeStamp = 3;
    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private long timeStamp_;
    /**
     * <code>required int64 timeStamp = 3;</code>
     */
    public boolean hasTimeStamp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 timeStamp = 3;</code>
     */
    public long getTimeStamp() {
      return timeStamp_;
    }

    // optional .Code code = 4;
    public static final int CODE_FIELD_NUMBER = 4;
    private org.cbzmq.game.enums.Code code_;
    /**
     * <code>optional .Code code = 4;</code>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .Code code = 4;</code>
     */
    public org.cbzmq.game.enums.Code getCode() {
      return code_;
    }

    // repeated .Character characterData = 5;
    public static final int CHARACTERDATA_FIELD_NUMBER = 5;
    private java.util.List<org.cbzmq.game.proto.CharacterProto.Character> characterData_;
    /**
     * <code>repeated .Character characterData = 5;</code>
     */
    public java.util.List<org.cbzmq.game.proto.CharacterProto.Character> getCharacterDataList() {
      return characterData_;
    }
    /**
     * <code>repeated .Character characterData = 5;</code>
     */
    public java.util.List<? extends org.cbzmq.game.proto.CharacterProto.CharacterOrBuilder> 
        getCharacterDataOrBuilderList() {
      return characterData_;
    }
    /**
     * <code>repeated .Character characterData = 5;</code>
     */
    public int getCharacterDataCount() {
      return characterData_.size();
    }
    /**
     * <code>repeated .Character characterData = 5;</code>
     */
    public org.cbzmq.game.proto.CharacterProto.Character getCharacterData(int index) {
      return characterData_.get(index);
    }
    /**
     * <code>repeated .Character characterData = 5;</code>
     */
    public org.cbzmq.game.proto.CharacterProto.CharacterOrBuilder getCharacterDataOrBuilder(
        int index) {
      return characterData_.get(index);
    }

    // repeated .Event events = 6;
    public static final int EVENTS_FIELD_NUMBER = 6;
    private java.util.List<org.cbzmq.game.proto.MsgProto.Event> events_;
    /**
     * <code>repeated .Event events = 6;</code>
     */
    public java.util.List<org.cbzmq.game.proto.MsgProto.Event> getEventsList() {
      return events_;
    }
    /**
     * <code>repeated .Event events = 6;</code>
     */
    public java.util.List<? extends org.cbzmq.game.proto.MsgProto.EventOrBuilder> 
        getEventsOrBuilderList() {
      return events_;
    }
    /**
     * <code>repeated .Event events = 6;</code>
     */
    public int getEventsCount() {
      return events_.size();
    }
    /**
     * <code>repeated .Event events = 6;</code>
     */
    public org.cbzmq.game.proto.MsgProto.Event getEvents(int index) {
      return events_.get(index);
    }
    /**
     * <code>repeated .Event events = 6;</code>
     */
    public org.cbzmq.game.proto.MsgProto.EventOrBuilder getEventsOrBuilder(
        int index) {
      return events_.get(index);
    }

    private void initFields() {
      id_ = 0L;
      header_ = org.cbzmq.game.enums.MsgHeader.SYNC_CHARACTERS_INFO;
      timeStamp_ = 0L;
      code_ = org.cbzmq.game.enums.Code.OK;
      characterData_ = java.util.Collections.emptyList();
      events_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHeader()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimeStamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getCharacterDataCount(); i++) {
        if (!getCharacterData(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getEventsCount(); i++) {
        if (!getEvents(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, header_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, timeStamp_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, code_.getNumber());
      }
      for (int i = 0; i < characterData_.size(); i++) {
        output.writeMessage(5, characterData_.get(i));
      }
      for (int i = 0; i < events_.size(); i++) {
        output.writeMessage(6, events_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, header_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, timeStamp_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, code_.getNumber());
      }
      for (int i = 0; i < characterData_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, characterData_.get(i));
      }
      for (int i = 0; i < events_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, events_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.cbzmq.game.proto.MsgProto.Msg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cbzmq.game.proto.MsgProto.Msg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cbzmq.game.proto.MsgProto.Msg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cbzmq.game.proto.MsgProto.Msg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cbzmq.game.proto.MsgProto.Msg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.cbzmq.game.proto.MsgProto.Msg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.cbzmq.game.proto.MsgProto.Msg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.cbzmq.game.proto.MsgProto.Msg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.cbzmq.game.proto.MsgProto.Msg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.cbzmq.game.proto.MsgProto.Msg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.cbzmq.game.proto.MsgProto.Msg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Msg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.cbzmq.game.proto.MsgProto.MsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.cbzmq.game.proto.MsgProto.internal_static_Msg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.cbzmq.game.proto.MsgProto.internal_static_Msg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.cbzmq.game.proto.MsgProto.Msg.class, org.cbzmq.game.proto.MsgProto.Msg.Builder.class);
      }

      // Construct using org.cbzmq.game.proto.MsgProto.Msg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getCharacterDataFieldBuilder();
          getEventsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        header_ = org.cbzmq.game.enums.MsgHeader.SYNC_CHARACTERS_INFO;
        bitField0_ = (bitField0_ & ~0x00000002);
        timeStamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        code_ = org.cbzmq.game.enums.Code.OK;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (characterDataBuilder_ == null) {
          characterData_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          characterDataBuilder_.clear();
        }
        if (eventsBuilder_ == null) {
          events_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          eventsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.cbzmq.game.proto.MsgProto.internal_static_Msg_descriptor;
      }

      public org.cbzmq.game.proto.MsgProto.Msg getDefaultInstanceForType() {
        return org.cbzmq.game.proto.MsgProto.Msg.getDefaultInstance();
      }

      public org.cbzmq.game.proto.MsgProto.Msg build() {
        org.cbzmq.game.proto.MsgProto.Msg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.cbzmq.game.proto.MsgProto.Msg buildPartial() {
        org.cbzmq.game.proto.MsgProto.Msg result = new org.cbzmq.game.proto.MsgProto.Msg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.header_ = header_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.timeStamp_ = timeStamp_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.code_ = code_;
        if (characterDataBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            characterData_ = java.util.Collections.unmodifiableList(characterData_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.characterData_ = characterData_;
        } else {
          result.characterData_ = characterDataBuilder_.build();
        }
        if (eventsBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020)) {
            events_ = java.util.Collections.unmodifiableList(events_);
            bitField0_ = (bitField0_ & ~0x00000020);
          }
          result.events_ = events_;
        } else {
          result.events_ = eventsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.cbzmq.game.proto.MsgProto.Msg) {
          return mergeFrom((org.cbzmq.game.proto.MsgProto.Msg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.cbzmq.game.proto.MsgProto.Msg other) {
        if (other == org.cbzmq.game.proto.MsgProto.Msg.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasHeader()) {
          setHeader(other.getHeader());
        }
        if (other.hasTimeStamp()) {
          setTimeStamp(other.getTimeStamp());
        }
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (characterDataBuilder_ == null) {
          if (!other.characterData_.isEmpty()) {
            if (characterData_.isEmpty()) {
              characterData_ = other.characterData_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureCharacterDataIsMutable();
              characterData_.addAll(other.characterData_);
            }
            onChanged();
          }
        } else {
          if (!other.characterData_.isEmpty()) {
            if (characterDataBuilder_.isEmpty()) {
              characterDataBuilder_.dispose();
              characterDataBuilder_ = null;
              characterData_ = other.characterData_;
              bitField0_ = (bitField0_ & ~0x00000010);
              characterDataBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getCharacterDataFieldBuilder() : null;
            } else {
              characterDataBuilder_.addAllMessages(other.characterData_);
            }
          }
        }
        if (eventsBuilder_ == null) {
          if (!other.events_.isEmpty()) {
            if (events_.isEmpty()) {
              events_ = other.events_;
              bitField0_ = (bitField0_ & ~0x00000020);
            } else {
              ensureEventsIsMutable();
              events_.addAll(other.events_);
            }
            onChanged();
          }
        } else {
          if (!other.events_.isEmpty()) {
            if (eventsBuilder_.isEmpty()) {
              eventsBuilder_.dispose();
              eventsBuilder_ = null;
              events_ = other.events_;
              bitField0_ = (bitField0_ & ~0x00000020);
              eventsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getEventsFieldBuilder() : null;
            } else {
              eventsBuilder_.addAllMessages(other.events_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasHeader()) {
          
          return false;
        }
        if (!hasTimeStamp()) {
          
          return false;
        }
        for (int i = 0; i < getCharacterDataCount(); i++) {
          if (!getCharacterData(i).isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getEventsCount(); i++) {
          if (!getEvents(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.cbzmq.game.proto.MsgProto.Msg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.cbzmq.game.proto.MsgProto.Msg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 id = 1;
      private long id_ ;
      /**
       * <code>required int64 id = 1;</code>
       *
       * <pre>
       *自身属性
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 id = 1;</code>
       *
       * <pre>
       *自身属性
       * </pre>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>required int64 id = 1;</code>
       *
       * <pre>
       *自身属性
       * </pre>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 id = 1;</code>
       *
       * <pre>
       *自身属性
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      // required .MsgHeader header = 2;
      private org.cbzmq.game.enums.MsgHeader header_ = org.cbzmq.game.enums.MsgHeader.SYNC_CHARACTERS_INFO;
      /**
       * <code>required .MsgHeader header = 2;</code>
       */
      public boolean hasHeader() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .MsgHeader header = 2;</code>
       */
      public org.cbzmq.game.enums.MsgHeader getHeader() {
        return header_;
      }
      /**
       * <code>required .MsgHeader header = 2;</code>
       */
      public Builder setHeader(org.cbzmq.game.enums.MsgHeader value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        header_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .MsgHeader header = 2;</code>
       */
      public Builder clearHeader() {
        bitField0_ = (bitField0_ & ~0x00000002);
        header_ = org.cbzmq.game.enums.MsgHeader.SYNC_CHARACTERS_INFO;
        onChanged();
        return this;
      }

      // required int64 timeStamp = 3;
      private long timeStamp_ ;
      /**
       * <code>required int64 timeStamp = 3;</code>
       */
      public boolean hasTimeStamp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 timeStamp = 3;</code>
       */
      public long getTimeStamp() {
        return timeStamp_;
      }
      /**
       * <code>required int64 timeStamp = 3;</code>
       */
      public Builder setTimeStamp(long value) {
        bitField0_ |= 0x00000004;
        timeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 timeStamp = 3;</code>
       */
      public Builder clearTimeStamp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timeStamp_ = 0L;
        onChanged();
        return this;
      }

      // optional .Code code = 4;
      private org.cbzmq.game.enums.Code code_ = org.cbzmq.game.enums.Code.OK;
      /**
       * <code>optional .Code code = 4;</code>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .Code code = 4;</code>
       */
      public org.cbzmq.game.enums.Code getCode() {
        return code_;
      }
      /**
       * <code>optional .Code code = 4;</code>
       */
      public Builder setCode(org.cbzmq.game.enums.Code value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .Code code = 4;</code>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000008);
        code_ = org.cbzmq.game.enums.Code.OK;
        onChanged();
        return this;
      }

      // repeated .Character characterData = 5;
      private java.util.List<org.cbzmq.game.proto.CharacterProto.Character> characterData_ =
        java.util.Collections.emptyList();
      private void ensureCharacterDataIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          characterData_ = new java.util.ArrayList<org.cbzmq.game.proto.CharacterProto.Character>(characterData_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.cbzmq.game.proto.CharacterProto.Character, org.cbzmq.game.proto.CharacterProto.Character.Builder, org.cbzmq.game.proto.CharacterProto.CharacterOrBuilder> characterDataBuilder_;

      /**
       * <code>repeated .Character characterData = 5;</code>
       */
      public java.util.List<org.cbzmq.game.proto.CharacterProto.Character> getCharacterDataList() {
        if (characterDataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(characterData_);
        } else {
          return characterDataBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Character characterData = 5;</code>
       */
      public int getCharacterDataCount() {
        if (characterDataBuilder_ == null) {
          return characterData_.size();
        } else {
          return characterDataBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Character characterData = 5;</code>
       */
      public org.cbzmq.game.proto.CharacterProto.Character getCharacterData(int index) {
        if (characterDataBuilder_ == null) {
          return characterData_.get(index);
        } else {
          return characterDataBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Character characterData = 5;</code>
       */
      public Builder setCharacterData(
          int index, org.cbzmq.game.proto.CharacterProto.Character value) {
        if (characterDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCharacterDataIsMutable();
          characterData_.set(index, value);
          onChanged();
        } else {
          characterDataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Character characterData = 5;</code>
       */
      public Builder setCharacterData(
          int index, org.cbzmq.game.proto.CharacterProto.Character.Builder builderForValue) {
        if (characterDataBuilder_ == null) {
          ensureCharacterDataIsMutable();
          characterData_.set(index, builderForValue.build());
          onChanged();
        } else {
          characterDataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Character characterData = 5;</code>
       */
      public Builder addCharacterData(org.cbzmq.game.proto.CharacterProto.Character value) {
        if (characterDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCharacterDataIsMutable();
          characterData_.add(value);
          onChanged();
        } else {
          characterDataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Character characterData = 5;</code>
       */
      public Builder addCharacterData(
          int index, org.cbzmq.game.proto.CharacterProto.Character value) {
        if (characterDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCharacterDataIsMutable();
          characterData_.add(index, value);
          onChanged();
        } else {
          characterDataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Character characterData = 5;</code>
       */
      public Builder addCharacterData(
          org.cbzmq.game.proto.CharacterProto.Character.Builder builderForValue) {
        if (characterDataBuilder_ == null) {
          ensureCharacterDataIsMutable();
          characterData_.add(builderForValue.build());
          onChanged();
        } else {
          characterDataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Character characterData = 5;</code>
       */
      public Builder addCharacterData(
          int index, org.cbzmq.game.proto.CharacterProto.Character.Builder builderForValue) {
        if (characterDataBuilder_ == null) {
          ensureCharacterDataIsMutable();
          characterData_.add(index, builderForValue.build());
          onChanged();
        } else {
          characterDataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Character characterData = 5;</code>
       */
      public Builder addAllCharacterData(
          java.lang.Iterable<? extends org.cbzmq.game.proto.CharacterProto.Character> values) {
        if (characterDataBuilder_ == null) {
          ensureCharacterDataIsMutable();
          super.addAll(values, characterData_);
          onChanged();
        } else {
          characterDataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Character characterData = 5;</code>
       */
      public Builder clearCharacterData() {
        if (characterDataBuilder_ == null) {
          characterData_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          characterDataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Character characterData = 5;</code>
       */
      public Builder removeCharacterData(int index) {
        if (characterDataBuilder_ == null) {
          ensureCharacterDataIsMutable();
          characterData_.remove(index);
          onChanged();
        } else {
          characterDataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Character characterData = 5;</code>
       */
      public org.cbzmq.game.proto.CharacterProto.Character.Builder getCharacterDataBuilder(
          int index) {
        return getCharacterDataFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Character characterData = 5;</code>
       */
      public org.cbzmq.game.proto.CharacterProto.CharacterOrBuilder getCharacterDataOrBuilder(
          int index) {
        if (characterDataBuilder_ == null) {
          return characterData_.get(index);  } else {
          return characterDataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Character characterData = 5;</code>
       */
      public java.util.List<? extends org.cbzmq.game.proto.CharacterProto.CharacterOrBuilder> 
           getCharacterDataOrBuilderList() {
        if (characterDataBuilder_ != null) {
          return characterDataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(characterData_);
        }
      }
      /**
       * <code>repeated .Character characterData = 5;</code>
       */
      public org.cbzmq.game.proto.CharacterProto.Character.Builder addCharacterDataBuilder() {
        return getCharacterDataFieldBuilder().addBuilder(
            org.cbzmq.game.proto.CharacterProto.Character.getDefaultInstance());
      }
      /**
       * <code>repeated .Character characterData = 5;</code>
       */
      public org.cbzmq.game.proto.CharacterProto.Character.Builder addCharacterDataBuilder(
          int index) {
        return getCharacterDataFieldBuilder().addBuilder(
            index, org.cbzmq.game.proto.CharacterProto.Character.getDefaultInstance());
      }
      /**
       * <code>repeated .Character characterData = 5;</code>
       */
      public java.util.List<org.cbzmq.game.proto.CharacterProto.Character.Builder> 
           getCharacterDataBuilderList() {
        return getCharacterDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.cbzmq.game.proto.CharacterProto.Character, org.cbzmq.game.proto.CharacterProto.Character.Builder, org.cbzmq.game.proto.CharacterProto.CharacterOrBuilder> 
          getCharacterDataFieldBuilder() {
        if (characterDataBuilder_ == null) {
          characterDataBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.cbzmq.game.proto.CharacterProto.Character, org.cbzmq.game.proto.CharacterProto.Character.Builder, org.cbzmq.game.proto.CharacterProto.CharacterOrBuilder>(
                  characterData_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          characterData_ = null;
        }
        return characterDataBuilder_;
      }

      // repeated .Event events = 6;
      private java.util.List<org.cbzmq.game.proto.MsgProto.Event> events_ =
        java.util.Collections.emptyList();
      private void ensureEventsIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          events_ = new java.util.ArrayList<org.cbzmq.game.proto.MsgProto.Event>(events_);
          bitField0_ |= 0x00000020;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.cbzmq.game.proto.MsgProto.Event, org.cbzmq.game.proto.MsgProto.Event.Builder, org.cbzmq.game.proto.MsgProto.EventOrBuilder> eventsBuilder_;

      /**
       * <code>repeated .Event events = 6;</code>
       */
      public java.util.List<org.cbzmq.game.proto.MsgProto.Event> getEventsList() {
        if (eventsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(events_);
        } else {
          return eventsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Event events = 6;</code>
       */
      public int getEventsCount() {
        if (eventsBuilder_ == null) {
          return events_.size();
        } else {
          return eventsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Event events = 6;</code>
       */
      public org.cbzmq.game.proto.MsgProto.Event getEvents(int index) {
        if (eventsBuilder_ == null) {
          return events_.get(index);
        } else {
          return eventsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Event events = 6;</code>
       */
      public Builder setEvents(
          int index, org.cbzmq.game.proto.MsgProto.Event value) {
        if (eventsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEventsIsMutable();
          events_.set(index, value);
          onChanged();
        } else {
          eventsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Event events = 6;</code>
       */
      public Builder setEvents(
          int index, org.cbzmq.game.proto.MsgProto.Event.Builder builderForValue) {
        if (eventsBuilder_ == null) {
          ensureEventsIsMutable();
          events_.set(index, builderForValue.build());
          onChanged();
        } else {
          eventsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Event events = 6;</code>
       */
      public Builder addEvents(org.cbzmq.game.proto.MsgProto.Event value) {
        if (eventsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEventsIsMutable();
          events_.add(value);
          onChanged();
        } else {
          eventsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Event events = 6;</code>
       */
      public Builder addEvents(
          int index, org.cbzmq.game.proto.MsgProto.Event value) {
        if (eventsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEventsIsMutable();
          events_.add(index, value);
          onChanged();
        } else {
          eventsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Event events = 6;</code>
       */
      public Builder addEvents(
          org.cbzmq.game.proto.MsgProto.Event.Builder builderForValue) {
        if (eventsBuilder_ == null) {
          ensureEventsIsMutable();
          events_.add(builderForValue.build());
          onChanged();
        } else {
          eventsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Event events = 6;</code>
       */
      public Builder addEvents(
          int index, org.cbzmq.game.proto.MsgProto.Event.Builder builderForValue) {
        if (eventsBuilder_ == null) {
          ensureEventsIsMutable();
          events_.add(index, builderForValue.build());
          onChanged();
        } else {
          eventsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Event events = 6;</code>
       */
      public Builder addAllEvents(
          java.lang.Iterable<? extends org.cbzmq.game.proto.MsgProto.Event> values) {
        if (eventsBuilder_ == null) {
          ensureEventsIsMutable();
          super.addAll(values, events_);
          onChanged();
        } else {
          eventsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Event events = 6;</code>
       */
      public Builder clearEvents() {
        if (eventsBuilder_ == null) {
          events_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
          onChanged();
        } else {
          eventsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Event events = 6;</code>
       */
      public Builder removeEvents(int index) {
        if (eventsBuilder_ == null) {
          ensureEventsIsMutable();
          events_.remove(index);
          onChanged();
        } else {
          eventsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Event events = 6;</code>
       */
      public org.cbzmq.game.proto.MsgProto.Event.Builder getEventsBuilder(
          int index) {
        return getEventsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Event events = 6;</code>
       */
      public org.cbzmq.game.proto.MsgProto.EventOrBuilder getEventsOrBuilder(
          int index) {
        if (eventsBuilder_ == null) {
          return events_.get(index);  } else {
          return eventsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Event events = 6;</code>
       */
      public java.util.List<? extends org.cbzmq.game.proto.MsgProto.EventOrBuilder> 
           getEventsOrBuilderList() {
        if (eventsBuilder_ != null) {
          return eventsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(events_);
        }
      }
      /**
       * <code>repeated .Event events = 6;</code>
       */
      public org.cbzmq.game.proto.MsgProto.Event.Builder addEventsBuilder() {
        return getEventsFieldBuilder().addBuilder(
            org.cbzmq.game.proto.MsgProto.Event.getDefaultInstance());
      }
      /**
       * <code>repeated .Event events = 6;</code>
       */
      public org.cbzmq.game.proto.MsgProto.Event.Builder addEventsBuilder(
          int index) {
        return getEventsFieldBuilder().addBuilder(
            index, org.cbzmq.game.proto.MsgProto.Event.getDefaultInstance());
      }
      /**
       * <code>repeated .Event events = 6;</code>
       */
      public java.util.List<org.cbzmq.game.proto.MsgProto.Event.Builder> 
           getEventsBuilderList() {
        return getEventsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.cbzmq.game.proto.MsgProto.Event, org.cbzmq.game.proto.MsgProto.Event.Builder, org.cbzmq.game.proto.MsgProto.EventOrBuilder> 
          getEventsFieldBuilder() {
        if (eventsBuilder_ == null) {
          eventsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.cbzmq.game.proto.MsgProto.Event, org.cbzmq.game.proto.MsgProto.Event.Builder, org.cbzmq.game.proto.MsgProto.EventOrBuilder>(
                  events_,
                  ((bitField0_ & 0x00000020) == 0x00000020),
                  getParentForChildren(),
                  isClean());
          events_ = null;
        }
        return eventsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Msg)
    }

    static {
      defaultInstance = new Msg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Msg)
  }

  public interface EventOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .OneBodyEventType oneBodyEvent = 2;
    /**
     * <code>optional .OneBodyEventType oneBodyEvent = 2;</code>
     */
    boolean hasOneBodyEvent();
    /**
     * <code>optional .OneBodyEventType oneBodyEvent = 2;</code>
     */
    org.cbzmq.game.enums.OneBodyEventType getOneBodyEvent();

    // optional .TwoBodyEventType towBodyEvent = 3;
    /**
     * <code>optional .TwoBodyEventType towBodyEvent = 3;</code>
     */
    boolean hasTowBodyEvent();
    /**
     * <code>optional .TwoBodyEventType towBodyEvent = 3;</code>
     */
    org.cbzmq.game.enums.TwoBodyEventType getTowBodyEvent();

    // optional .Character one = 4;
    /**
     * <code>optional .Character one = 4;</code>
     */
    boolean hasOne();
    /**
     * <code>optional .Character one = 4;</code>
     */
    org.cbzmq.game.proto.CharacterProto.Character getOne();
    /**
     * <code>optional .Character one = 4;</code>
     */
    org.cbzmq.game.proto.CharacterProto.CharacterOrBuilder getOneOrBuilder();

    // optional .Character other = 5;
    /**
     * <code>optional .Character other = 5;</code>
     */
    boolean hasOther();
    /**
     * <code>optional .Character other = 5;</code>
     */
    org.cbzmq.game.proto.CharacterProto.Character getOther();
    /**
     * <code>optional .Character other = 5;</code>
     */
    org.cbzmq.game.proto.CharacterProto.CharacterOrBuilder getOtherOrBuilder();

    // optional float floatData = 6;
    /**
     * <code>optional float floatData = 6;</code>
     */
    boolean hasFloatData();
    /**
     * <code>optional float floatData = 6;</code>
     */
    float getFloatData();

    // optional .Vector2 vector = 7;
    /**
     * <code>optional .Vector2 vector = 7;</code>
     */
    boolean hasVector();
    /**
     * <code>optional .Vector2 vector = 7;</code>
     */
    org.cbzmq.game.proto.CharacterProto.Vector2 getVector();
    /**
     * <code>optional .Vector2 vector = 7;</code>
     */
    org.cbzmq.game.proto.CharacterProto.Vector2OrBuilder getVectorOrBuilder();

    // optional .CharacterState state = 8;
    /**
     * <code>optional .CharacterState state = 8;</code>
     */
    boolean hasState();
    /**
     * <code>optional .CharacterState state = 8;</code>
     */
    org.cbzmq.game.enums.CharacterState getState();
  }
  /**
   * Protobuf type {@code Event}
   */
  public static final class Event extends
      com.google.protobuf.GeneratedMessage
      implements EventOrBuilder {
    // Use Event.newBuilder() to construct.
    private Event(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Event(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Event defaultInstance;
    public static Event getDefaultInstance() {
      return defaultInstance;
    }

    public Event getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Event(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              org.cbzmq.game.enums.OneBodyEventType value = org.cbzmq.game.enums.OneBodyEventType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                oneBodyEvent_ = value;
              }
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              org.cbzmq.game.enums.TwoBodyEventType value = org.cbzmq.game.enums.TwoBodyEventType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                towBodyEvent_ = value;
              }
              break;
            }
            case 34: {
              org.cbzmq.game.proto.CharacterProto.Character.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = one_.toBuilder();
              }
              one_ = input.readMessage(org.cbzmq.game.proto.CharacterProto.Character.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(one_);
                one_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 42: {
              org.cbzmq.game.proto.CharacterProto.Character.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = other_.toBuilder();
              }
              other_ = input.readMessage(org.cbzmq.game.proto.CharacterProto.Character.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(other_);
                other_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            case 53: {
              bitField0_ |= 0x00000010;
              floatData_ = input.readFloat();
              break;
            }
            case 58: {
              org.cbzmq.game.proto.CharacterProto.Vector2.Builder subBuilder = null;
              if (((bitField0_ & 0x00000020) == 0x00000020)) {
                subBuilder = vector_.toBuilder();
              }
              vector_ = input.readMessage(org.cbzmq.game.proto.CharacterProto.Vector2.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(vector_);
                vector_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000020;
              break;
            }
            case 64: {
              int rawValue = input.readEnum();
              org.cbzmq.game.enums.CharacterState value = org.cbzmq.game.enums.CharacterState.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(8, rawValue);
              } else {
                bitField0_ |= 0x00000040;
                state_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.cbzmq.game.proto.MsgProto.internal_static_Event_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.cbzmq.game.proto.MsgProto.internal_static_Event_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.cbzmq.game.proto.MsgProto.Event.class, org.cbzmq.game.proto.MsgProto.Event.Builder.class);
    }

    public static com.google.protobuf.Parser<Event> PARSER =
        new com.google.protobuf.AbstractParser<Event>() {
      public Event parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Event(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Event> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .OneBodyEventType oneBodyEvent = 2;
    public static final int ONEBODYEVENT_FIELD_NUMBER = 2;
    private org.cbzmq.game.enums.OneBodyEventType oneBodyEvent_;
    /**
     * <code>optional .OneBodyEventType oneBodyEvent = 2;</code>
     */
    public boolean hasOneBodyEvent() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .OneBodyEventType oneBodyEvent = 2;</code>
     */
    public org.cbzmq.game.enums.OneBodyEventType getOneBodyEvent() {
      return oneBodyEvent_;
    }

    // optional .TwoBodyEventType towBodyEvent = 3;
    public static final int TOWBODYEVENT_FIELD_NUMBER = 3;
    private org.cbzmq.game.enums.TwoBodyEventType towBodyEvent_;
    /**
     * <code>optional .TwoBodyEventType towBodyEvent = 3;</code>
     */
    public boolean hasTowBodyEvent() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .TwoBodyEventType towBodyEvent = 3;</code>
     */
    public org.cbzmq.game.enums.TwoBodyEventType getTowBodyEvent() {
      return towBodyEvent_;
    }

    // optional .Character one = 4;
    public static final int ONE_FIELD_NUMBER = 4;
    private org.cbzmq.game.proto.CharacterProto.Character one_;
    /**
     * <code>optional .Character one = 4;</code>
     */
    public boolean hasOne() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .Character one = 4;</code>
     */
    public org.cbzmq.game.proto.CharacterProto.Character getOne() {
      return one_;
    }
    /**
     * <code>optional .Character one = 4;</code>
     */
    public org.cbzmq.game.proto.CharacterProto.CharacterOrBuilder getOneOrBuilder() {
      return one_;
    }

    // optional .Character other = 5;
    public static final int OTHER_FIELD_NUMBER = 5;
    private org.cbzmq.game.proto.CharacterProto.Character other_;
    /**
     * <code>optional .Character other = 5;</code>
     */
    public boolean hasOther() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .Character other = 5;</code>
     */
    public org.cbzmq.game.proto.CharacterProto.Character getOther() {
      return other_;
    }
    /**
     * <code>optional .Character other = 5;</code>
     */
    public org.cbzmq.game.proto.CharacterProto.CharacterOrBuilder getOtherOrBuilder() {
      return other_;
    }

    // optional float floatData = 6;
    public static final int FLOATDATA_FIELD_NUMBER = 6;
    private float floatData_;
    /**
     * <code>optional float floatData = 6;</code>
     */
    public boolean hasFloatData() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional float floatData = 6;</code>
     */
    public float getFloatData() {
      return floatData_;
    }

    // optional .Vector2 vector = 7;
    public static final int VECTOR_FIELD_NUMBER = 7;
    private org.cbzmq.game.proto.CharacterProto.Vector2 vector_;
    /**
     * <code>optional .Vector2 vector = 7;</code>
     */
    public boolean hasVector() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional .Vector2 vector = 7;</code>
     */
    public org.cbzmq.game.proto.CharacterProto.Vector2 getVector() {
      return vector_;
    }
    /**
     * <code>optional .Vector2 vector = 7;</code>
     */
    public org.cbzmq.game.proto.CharacterProto.Vector2OrBuilder getVectorOrBuilder() {
      return vector_;
    }

    // optional .CharacterState state = 8;
    public static final int STATE_FIELD_NUMBER = 8;
    private org.cbzmq.game.enums.CharacterState state_;
    /**
     * <code>optional .CharacterState state = 8;</code>
     */
    public boolean hasState() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional .CharacterState state = 8;</code>
     */
    public org.cbzmq.game.enums.CharacterState getState() {
      return state_;
    }

    private void initFields() {
      oneBodyEvent_ = org.cbzmq.game.enums.OneBodyEventType.born;
      towBodyEvent_ = org.cbzmq.game.enums.TwoBodyEventType.collisionCharacter;
      one_ = org.cbzmq.game.proto.CharacterProto.Character.getDefaultInstance();
      other_ = org.cbzmq.game.proto.CharacterProto.Character.getDefaultInstance();
      floatData_ = 0F;
      vector_ = org.cbzmq.game.proto.CharacterProto.Vector2.getDefaultInstance();
      state_ = org.cbzmq.game.enums.CharacterState.idle;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (hasOne()) {
        if (!getOne().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasOther()) {
        if (!getOther().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasVector()) {
        if (!getVector().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(2, oneBodyEvent_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(3, towBodyEvent_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(4, one_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(5, other_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeFloat(6, floatData_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeMessage(7, vector_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeEnum(8, state_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, oneBodyEvent_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, towBodyEvent_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, one_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, other_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, floatData_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, vector_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, state_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.cbzmq.game.proto.MsgProto.Event parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cbzmq.game.proto.MsgProto.Event parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cbzmq.game.proto.MsgProto.Event parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cbzmq.game.proto.MsgProto.Event parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cbzmq.game.proto.MsgProto.Event parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.cbzmq.game.proto.MsgProto.Event parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.cbzmq.game.proto.MsgProto.Event parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.cbzmq.game.proto.MsgProto.Event parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.cbzmq.game.proto.MsgProto.Event parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.cbzmq.game.proto.MsgProto.Event parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.cbzmq.game.proto.MsgProto.Event prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Event}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.cbzmq.game.proto.MsgProto.EventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.cbzmq.game.proto.MsgProto.internal_static_Event_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.cbzmq.game.proto.MsgProto.internal_static_Event_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.cbzmq.game.proto.MsgProto.Event.class, org.cbzmq.game.proto.MsgProto.Event.Builder.class);
      }

      // Construct using org.cbzmq.game.proto.MsgProto.Event.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getOneFieldBuilder();
          getOtherFieldBuilder();
          getVectorFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        oneBodyEvent_ = org.cbzmq.game.enums.OneBodyEventType.born;
        bitField0_ = (bitField0_ & ~0x00000001);
        towBodyEvent_ = org.cbzmq.game.enums.TwoBodyEventType.collisionCharacter;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (oneBuilder_ == null) {
          one_ = org.cbzmq.game.proto.CharacterProto.Character.getDefaultInstance();
        } else {
          oneBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (otherBuilder_ == null) {
          other_ = org.cbzmq.game.proto.CharacterProto.Character.getDefaultInstance();
        } else {
          otherBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        floatData_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000010);
        if (vectorBuilder_ == null) {
          vector_ = org.cbzmq.game.proto.CharacterProto.Vector2.getDefaultInstance();
        } else {
          vectorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        state_ = org.cbzmq.game.enums.CharacterState.idle;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.cbzmq.game.proto.MsgProto.internal_static_Event_descriptor;
      }

      public org.cbzmq.game.proto.MsgProto.Event getDefaultInstanceForType() {
        return org.cbzmq.game.proto.MsgProto.Event.getDefaultInstance();
      }

      public org.cbzmq.game.proto.MsgProto.Event build() {
        org.cbzmq.game.proto.MsgProto.Event result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.cbzmq.game.proto.MsgProto.Event buildPartial() {
        org.cbzmq.game.proto.MsgProto.Event result = new org.cbzmq.game.proto.MsgProto.Event(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.oneBodyEvent_ = oneBodyEvent_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.towBodyEvent_ = towBodyEvent_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (oneBuilder_ == null) {
          result.one_ = one_;
        } else {
          result.one_ = oneBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (otherBuilder_ == null) {
          result.other_ = other_;
        } else {
          result.other_ = otherBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.floatData_ = floatData_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        if (vectorBuilder_ == null) {
          result.vector_ = vector_;
        } else {
          result.vector_ = vectorBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.state_ = state_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.cbzmq.game.proto.MsgProto.Event) {
          return mergeFrom((org.cbzmq.game.proto.MsgProto.Event)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.cbzmq.game.proto.MsgProto.Event other) {
        if (other == org.cbzmq.game.proto.MsgProto.Event.getDefaultInstance()) return this;
        if (other.hasOneBodyEvent()) {
          setOneBodyEvent(other.getOneBodyEvent());
        }
        if (other.hasTowBodyEvent()) {
          setTowBodyEvent(other.getTowBodyEvent());
        }
        if (other.hasOne()) {
          mergeOne(other.getOne());
        }
        if (other.hasOther()) {
          mergeOther(other.getOther());
        }
        if (other.hasFloatData()) {
          setFloatData(other.getFloatData());
        }
        if (other.hasVector()) {
          mergeVector(other.getVector());
        }
        if (other.hasState()) {
          setState(other.getState());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (hasOne()) {
          if (!getOne().isInitialized()) {
            
            return false;
          }
        }
        if (hasOther()) {
          if (!getOther().isInitialized()) {
            
            return false;
          }
        }
        if (hasVector()) {
          if (!getVector().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.cbzmq.game.proto.MsgProto.Event parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.cbzmq.game.proto.MsgProto.Event) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .OneBodyEventType oneBodyEvent = 2;
      private org.cbzmq.game.enums.OneBodyEventType oneBodyEvent_ = org.cbzmq.game.enums.OneBodyEventType.born;
      /**
       * <code>optional .OneBodyEventType oneBodyEvent = 2;</code>
       */
      public boolean hasOneBodyEvent() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .OneBodyEventType oneBodyEvent = 2;</code>
       */
      public org.cbzmq.game.enums.OneBodyEventType getOneBodyEvent() {
        return oneBodyEvent_;
      }
      /**
       * <code>optional .OneBodyEventType oneBodyEvent = 2;</code>
       */
      public Builder setOneBodyEvent(org.cbzmq.game.enums.OneBodyEventType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        oneBodyEvent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .OneBodyEventType oneBodyEvent = 2;</code>
       */
      public Builder clearOneBodyEvent() {
        bitField0_ = (bitField0_ & ~0x00000001);
        oneBodyEvent_ = org.cbzmq.game.enums.OneBodyEventType.born;
        onChanged();
        return this;
      }

      // optional .TwoBodyEventType towBodyEvent = 3;
      private org.cbzmq.game.enums.TwoBodyEventType towBodyEvent_ = org.cbzmq.game.enums.TwoBodyEventType.collisionCharacter;
      /**
       * <code>optional .TwoBodyEventType towBodyEvent = 3;</code>
       */
      public boolean hasTowBodyEvent() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .TwoBodyEventType towBodyEvent = 3;</code>
       */
      public org.cbzmq.game.enums.TwoBodyEventType getTowBodyEvent() {
        return towBodyEvent_;
      }
      /**
       * <code>optional .TwoBodyEventType towBodyEvent = 3;</code>
       */
      public Builder setTowBodyEvent(org.cbzmq.game.enums.TwoBodyEventType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        towBodyEvent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .TwoBodyEventType towBodyEvent = 3;</code>
       */
      public Builder clearTowBodyEvent() {
        bitField0_ = (bitField0_ & ~0x00000002);
        towBodyEvent_ = org.cbzmq.game.enums.TwoBodyEventType.collisionCharacter;
        onChanged();
        return this;
      }

      // optional .Character one = 4;
      private org.cbzmq.game.proto.CharacterProto.Character one_ = org.cbzmq.game.proto.CharacterProto.Character.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.cbzmq.game.proto.CharacterProto.Character, org.cbzmq.game.proto.CharacterProto.Character.Builder, org.cbzmq.game.proto.CharacterProto.CharacterOrBuilder> oneBuilder_;
      /**
       * <code>optional .Character one = 4;</code>
       */
      public boolean hasOne() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .Character one = 4;</code>
       */
      public org.cbzmq.game.proto.CharacterProto.Character getOne() {
        if (oneBuilder_ == null) {
          return one_;
        } else {
          return oneBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Character one = 4;</code>
       */
      public Builder setOne(org.cbzmq.game.proto.CharacterProto.Character value) {
        if (oneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          one_ = value;
          onChanged();
        } else {
          oneBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Character one = 4;</code>
       */
      public Builder setOne(
          org.cbzmq.game.proto.CharacterProto.Character.Builder builderForValue) {
        if (oneBuilder_ == null) {
          one_ = builderForValue.build();
          onChanged();
        } else {
          oneBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Character one = 4;</code>
       */
      public Builder mergeOne(org.cbzmq.game.proto.CharacterProto.Character value) {
        if (oneBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              one_ != org.cbzmq.game.proto.CharacterProto.Character.getDefaultInstance()) {
            one_ =
              org.cbzmq.game.proto.CharacterProto.Character.newBuilder(one_).mergeFrom(value).buildPartial();
          } else {
            one_ = value;
          }
          onChanged();
        } else {
          oneBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Character one = 4;</code>
       */
      public Builder clearOne() {
        if (oneBuilder_ == null) {
          one_ = org.cbzmq.game.proto.CharacterProto.Character.getDefaultInstance();
          onChanged();
        } else {
          oneBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .Character one = 4;</code>
       */
      public org.cbzmq.game.proto.CharacterProto.Character.Builder getOneBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getOneFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Character one = 4;</code>
       */
      public org.cbzmq.game.proto.CharacterProto.CharacterOrBuilder getOneOrBuilder() {
        if (oneBuilder_ != null) {
          return oneBuilder_.getMessageOrBuilder();
        } else {
          return one_;
        }
      }
      /**
       * <code>optional .Character one = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.cbzmq.game.proto.CharacterProto.Character, org.cbzmq.game.proto.CharacterProto.Character.Builder, org.cbzmq.game.proto.CharacterProto.CharacterOrBuilder> 
          getOneFieldBuilder() {
        if (oneBuilder_ == null) {
          oneBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.cbzmq.game.proto.CharacterProto.Character, org.cbzmq.game.proto.CharacterProto.Character.Builder, org.cbzmq.game.proto.CharacterProto.CharacterOrBuilder>(
                  one_,
                  getParentForChildren(),
                  isClean());
          one_ = null;
        }
        return oneBuilder_;
      }

      // optional .Character other = 5;
      private org.cbzmq.game.proto.CharacterProto.Character other_ = org.cbzmq.game.proto.CharacterProto.Character.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.cbzmq.game.proto.CharacterProto.Character, org.cbzmq.game.proto.CharacterProto.Character.Builder, org.cbzmq.game.proto.CharacterProto.CharacterOrBuilder> otherBuilder_;
      /**
       * <code>optional .Character other = 5;</code>
       */
      public boolean hasOther() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .Character other = 5;</code>
       */
      public org.cbzmq.game.proto.CharacterProto.Character getOther() {
        if (otherBuilder_ == null) {
          return other_;
        } else {
          return otherBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Character other = 5;</code>
       */
      public Builder setOther(org.cbzmq.game.proto.CharacterProto.Character value) {
        if (otherBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          other_ = value;
          onChanged();
        } else {
          otherBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Character other = 5;</code>
       */
      public Builder setOther(
          org.cbzmq.game.proto.CharacterProto.Character.Builder builderForValue) {
        if (otherBuilder_ == null) {
          other_ = builderForValue.build();
          onChanged();
        } else {
          otherBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Character other = 5;</code>
       */
      public Builder mergeOther(org.cbzmq.game.proto.CharacterProto.Character value) {
        if (otherBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              other_ != org.cbzmq.game.proto.CharacterProto.Character.getDefaultInstance()) {
            other_ =
              org.cbzmq.game.proto.CharacterProto.Character.newBuilder(other_).mergeFrom(value).buildPartial();
          } else {
            other_ = value;
          }
          onChanged();
        } else {
          otherBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Character other = 5;</code>
       */
      public Builder clearOther() {
        if (otherBuilder_ == null) {
          other_ = org.cbzmq.game.proto.CharacterProto.Character.getDefaultInstance();
          onChanged();
        } else {
          otherBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .Character other = 5;</code>
       */
      public org.cbzmq.game.proto.CharacterProto.Character.Builder getOtherBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getOtherFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Character other = 5;</code>
       */
      public org.cbzmq.game.proto.CharacterProto.CharacterOrBuilder getOtherOrBuilder() {
        if (otherBuilder_ != null) {
          return otherBuilder_.getMessageOrBuilder();
        } else {
          return other_;
        }
      }
      /**
       * <code>optional .Character other = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.cbzmq.game.proto.CharacterProto.Character, org.cbzmq.game.proto.CharacterProto.Character.Builder, org.cbzmq.game.proto.CharacterProto.CharacterOrBuilder> 
          getOtherFieldBuilder() {
        if (otherBuilder_ == null) {
          otherBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.cbzmq.game.proto.CharacterProto.Character, org.cbzmq.game.proto.CharacterProto.Character.Builder, org.cbzmq.game.proto.CharacterProto.CharacterOrBuilder>(
                  other_,
                  getParentForChildren(),
                  isClean());
          other_ = null;
        }
        return otherBuilder_;
      }

      // optional float floatData = 6;
      private float floatData_ ;
      /**
       * <code>optional float floatData = 6;</code>
       */
      public boolean hasFloatData() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional float floatData = 6;</code>
       */
      public float getFloatData() {
        return floatData_;
      }
      /**
       * <code>optional float floatData = 6;</code>
       */
      public Builder setFloatData(float value) {
        bitField0_ |= 0x00000010;
        floatData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float floatData = 6;</code>
       */
      public Builder clearFloatData() {
        bitField0_ = (bitField0_ & ~0x00000010);
        floatData_ = 0F;
        onChanged();
        return this;
      }

      // optional .Vector2 vector = 7;
      private org.cbzmq.game.proto.CharacterProto.Vector2 vector_ = org.cbzmq.game.proto.CharacterProto.Vector2.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.cbzmq.game.proto.CharacterProto.Vector2, org.cbzmq.game.proto.CharacterProto.Vector2.Builder, org.cbzmq.game.proto.CharacterProto.Vector2OrBuilder> vectorBuilder_;
      /**
       * <code>optional .Vector2 vector = 7;</code>
       */
      public boolean hasVector() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional .Vector2 vector = 7;</code>
       */
      public org.cbzmq.game.proto.CharacterProto.Vector2 getVector() {
        if (vectorBuilder_ == null) {
          return vector_;
        } else {
          return vectorBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Vector2 vector = 7;</code>
       */
      public Builder setVector(org.cbzmq.game.proto.CharacterProto.Vector2 value) {
        if (vectorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          vector_ = value;
          onChanged();
        } else {
          vectorBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .Vector2 vector = 7;</code>
       */
      public Builder setVector(
          org.cbzmq.game.proto.CharacterProto.Vector2.Builder builderForValue) {
        if (vectorBuilder_ == null) {
          vector_ = builderForValue.build();
          onChanged();
        } else {
          vectorBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .Vector2 vector = 7;</code>
       */
      public Builder mergeVector(org.cbzmq.game.proto.CharacterProto.Vector2 value) {
        if (vectorBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020) &&
              vector_ != org.cbzmq.game.proto.CharacterProto.Vector2.getDefaultInstance()) {
            vector_ =
              org.cbzmq.game.proto.CharacterProto.Vector2.newBuilder(vector_).mergeFrom(value).buildPartial();
          } else {
            vector_ = value;
          }
          onChanged();
        } else {
          vectorBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .Vector2 vector = 7;</code>
       */
      public Builder clearVector() {
        if (vectorBuilder_ == null) {
          vector_ = org.cbzmq.game.proto.CharacterProto.Vector2.getDefaultInstance();
          onChanged();
        } else {
          vectorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      /**
       * <code>optional .Vector2 vector = 7;</code>
       */
      public org.cbzmq.game.proto.CharacterProto.Vector2.Builder getVectorBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getVectorFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Vector2 vector = 7;</code>
       */
      public org.cbzmq.game.proto.CharacterProto.Vector2OrBuilder getVectorOrBuilder() {
        if (vectorBuilder_ != null) {
          return vectorBuilder_.getMessageOrBuilder();
        } else {
          return vector_;
        }
      }
      /**
       * <code>optional .Vector2 vector = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.cbzmq.game.proto.CharacterProto.Vector2, org.cbzmq.game.proto.CharacterProto.Vector2.Builder, org.cbzmq.game.proto.CharacterProto.Vector2OrBuilder> 
          getVectorFieldBuilder() {
        if (vectorBuilder_ == null) {
          vectorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.cbzmq.game.proto.CharacterProto.Vector2, org.cbzmq.game.proto.CharacterProto.Vector2.Builder, org.cbzmq.game.proto.CharacterProto.Vector2OrBuilder>(
                  vector_,
                  getParentForChildren(),
                  isClean());
          vector_ = null;
        }
        return vectorBuilder_;
      }

      // optional .CharacterState state = 8;
      private org.cbzmq.game.enums.CharacterState state_ = org.cbzmq.game.enums.CharacterState.idle;
      /**
       * <code>optional .CharacterState state = 8;</code>
       */
      public boolean hasState() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional .CharacterState state = 8;</code>
       */
      public org.cbzmq.game.enums.CharacterState getState() {
        return state_;
      }
      /**
       * <code>optional .CharacterState state = 8;</code>
       */
      public Builder setState(org.cbzmq.game.enums.CharacterState value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000040;
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .CharacterState state = 8;</code>
       */
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000040);
        state_ = org.cbzmq.game.enums.CharacterState.idle;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Event)
    }

    static {
      defaultInstance = new Event(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Event)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Msg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Msg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Event_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Event_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016avro/msg.proto\032\024avro/character.proto\032\020" +
      "avro/enums.proto\"\220\001\n\003Msg\022\n\n\002id\030\001 \002(\003\022\032\n\006" +
      "header\030\002 \002(\0162\n.MsgHeader\022\021\n\ttimeStamp\030\003 " +
      "\002(\003\022\023\n\004code\030\004 \001(\0162\005.Code\022!\n\rcharacterDat" +
      "a\030\005 \003(\0132\n.Character\022\026\n\006events\030\006 \003(\0132\006.Ev" +
      "ent\"\332\001\n\005Event\022\'\n\014oneBodyEvent\030\002 \001(\0162\021.On" +
      "eBodyEventType\022\'\n\014towBodyEvent\030\003 \001(\0162\021.T" +
      "woBodyEventType\022\027\n\003one\030\004 \001(\0132\n.Character" +
      "\022\031\n\005other\030\005 \001(\0132\n.Character\022\021\n\tfloatData" +
      "\030\006 \001(\002\022\030\n\006vector\030\007 \001(\0132\010.Vector2\022\036\n\005stat",
      "e\030\010 \001(\0162\017.CharacterStateB\"\n\024org.cbzmq.ga" +
      "me.protoB\010MsgProtoP\000"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Msg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Msg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Msg_descriptor,
              new java.lang.String[] { "Id", "Header", "TimeStamp", "Code", "CharacterData", "Events", });
          internal_static_Event_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Event_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Event_descriptor,
              new java.lang.String[] { "OneBodyEvent", "TowBodyEvent", "One", "Other", "FloatData", "Vector", "State", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.cbzmq.game.proto.CharacterProto.getDescriptor(),
          org.cbzmq.game.enums.Enums.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
