// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: element.proto

package awt.proto;

public final class ElementProto {
  private ElementProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_Element_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Element_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\relement.proto\032\013enums.proto\"\247\002\n\007Element" +
      "\022\020\n\010playerId\030\001 \001(\005\022!\n\013elementType\030\002 \001(\0162" +
      "\014.ElementType\022\023\n\013xCoordinate\030\003 \001(\005\022\023\n\013yC" +
      "oordinate\030\004 \001(\005\022\026\n\016mapXCoordinate\030\005 \001(\005\022" +
      "\026\n\016mapYCoordinate\030\006 \001(\005\022\027\n\006direct\030\007 \001(\0162" +
      "\007.Direct\022\017\n\007isMoved\030\010 \001(\010\022\016\n\006isLive\030\t \002(" +
      "\010\022\r\n\005blood\030\n \001(\005\022\022\n\nincreaseId\030\013 \002(\005\022\020\n\010" +
      "distance\030\014 \001(\005\022\036\n\rcanMoveDirect\030\r \001(\0162\007." +
      "DirectB\033\n\tawt.protoB\014ElementProtoP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Element_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Element_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Element_descriptor,
              new java.lang.String[] { "PlayerId", "ElementType", "XCoordinate", "YCoordinate", "MapXCoordinate", "MapYCoordinate", "Direct", "IsMoved", "IsLive", "Blood", "IncreaseId", "Distance", "CanMoveDirect", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          awt.proto.enums.Enums.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
