// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

package awt.proto;

/**
 * Protobuf type {@code Msg}
 */
public  final class Msg extends
    com.google.protobuf.GeneratedMessage
    implements MsgOrBuilder {
  // Use Msg.newBuilder() to construct.
  private Msg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private Msg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final Msg defaultInstance;
  public static Msg getDefaultInstance() {
    return defaultInstance;
  }

  public Msg getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private Msg(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();
            awt.proto.enums.MsgAction value = awt.proto.enums.MsgAction.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(1, rawValue);
            } else {
              bitField0_ |= 0x00000001;
              header_ = value;
            }
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              elements_ = new java.util.ArrayList<awt.proto.Element>();
              mutable_bitField0_ |= 0x00000002;
            }
            elements_.add(input.readMessage(awt.proto.Element.PARSER, extensionRegistry));
            break;
          }
          case 24: {
            bitField0_ |= 0x00000002;
            timeStamp_ = input.readInt64();
            break;
          }
          case 32: {
            int rawValue = input.readEnum();
            awt.proto.enums.Code value = awt.proto.enums.Code.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(4, rawValue);
            } else {
              bitField0_ |= 0x00000004;
              code_ = value;
            }
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              commands_ = new java.util.ArrayList<awt.proto.command.Command>();
              mutable_bitField0_ |= 0x00000010;
            }
            commands_.add(input.readMessage(awt.proto.command.Command.PARSER, extensionRegistry));
            break;
          }
          case 50: {
            awt.proto.Player.Builder subBuilder = null;
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
              subBuilder = player_.toBuilder();
            }
            player_ = input.readMessage(awt.proto.Player.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(player_);
              player_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000008;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        elements_ = java.util.Collections.unmodifiableList(elements_);
      }
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        commands_ = java.util.Collections.unmodifiableList(commands_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return awt.proto.MsgProto.internal_static_Msg_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return awt.proto.MsgProto.internal_static_Msg_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            awt.proto.Msg.class, awt.proto.Msg.Builder.class);
  }

  public static com.google.protobuf.Parser<Msg> PARSER =
      new com.google.protobuf.AbstractParser<Msg>() {
    public Msg parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Msg(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<Msg> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  // required .MsgAction header = 1;
  public static final int HEADER_FIELD_NUMBER = 1;
  private awt.proto.enums.MsgAction header_;
  /**
   * <code>required .MsgAction header = 1;</code>
   *
   * <pre>
   *自身属性
   * </pre>
   */
  public boolean hasHeader() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required .MsgAction header = 1;</code>
   *
   * <pre>
   *自身属性
   * </pre>
   */
  public awt.proto.enums.MsgAction getHeader() {
    return header_;
  }

  // repeated .Element elements = 2;
  public static final int ELEMENTS_FIELD_NUMBER = 2;
  private java.util.List<awt.proto.Element> elements_;
  /**
   * <code>repeated .Element elements = 2;</code>
   */
  public java.util.List<awt.proto.Element> getElementsList() {
    return elements_;
  }
  /**
   * <code>repeated .Element elements = 2;</code>
   */
  public java.util.List<? extends awt.proto.ElementOrBuilder> 
      getElementsOrBuilderList() {
    return elements_;
  }
  /**
   * <code>repeated .Element elements = 2;</code>
   */
  public int getElementsCount() {
    return elements_.size();
  }
  /**
   * <code>repeated .Element elements = 2;</code>
   */
  public awt.proto.Element getElements(int index) {
    return elements_.get(index);
  }
  /**
   * <code>repeated .Element elements = 2;</code>
   */
  public awt.proto.ElementOrBuilder getElementsOrBuilder(
      int index) {
    return elements_.get(index);
  }

  // required int64 timeStamp = 3;
  public static final int TIMESTAMP_FIELD_NUMBER = 3;
  private long timeStamp_;
  /**
   * <code>required int64 timeStamp = 3;</code>
   */
  public boolean hasTimeStamp() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required int64 timeStamp = 3;</code>
   */
  public long getTimeStamp() {
    return timeStamp_;
  }

  // optional .Code code = 4;
  public static final int CODE_FIELD_NUMBER = 4;
  private awt.proto.enums.Code code_;
  /**
   * <code>optional .Code code = 4;</code>
   */
  public boolean hasCode() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional .Code code = 4;</code>
   */
  public awt.proto.enums.Code getCode() {
    return code_;
  }

  // repeated .Command commands = 5;
  public static final int COMMANDS_FIELD_NUMBER = 5;
  private java.util.List<awt.proto.command.Command> commands_;
  /**
   * <code>repeated .Command commands = 5;</code>
   */
  public java.util.List<awt.proto.command.Command> getCommandsList() {
    return commands_;
  }
  /**
   * <code>repeated .Command commands = 5;</code>
   */
  public java.util.List<? extends awt.proto.command.CommandOrBuilder> 
      getCommandsOrBuilderList() {
    return commands_;
  }
  /**
   * <code>repeated .Command commands = 5;</code>
   */
  public int getCommandsCount() {
    return commands_.size();
  }
  /**
   * <code>repeated .Command commands = 5;</code>
   */
  public awt.proto.command.Command getCommands(int index) {
    return commands_.get(index);
  }
  /**
   * <code>repeated .Command commands = 5;</code>
   */
  public awt.proto.command.CommandOrBuilder getCommandsOrBuilder(
      int index) {
    return commands_.get(index);
  }

  // optional .Player player = 6;
  public static final int PLAYER_FIELD_NUMBER = 6;
  private awt.proto.Player player_;
  /**
   * <code>optional .Player player = 6;</code>
   */
  public boolean hasPlayer() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional .Player player = 6;</code>
   */
  public awt.proto.Player getPlayer() {
    return player_;
  }
  /**
   * <code>optional .Player player = 6;</code>
   */
  public awt.proto.PlayerOrBuilder getPlayerOrBuilder() {
    return player_;
  }

  private void initFields() {
    header_ = awt.proto.enums.MsgAction.LOGIN;
    elements_ = java.util.Collections.emptyList();
    timeStamp_ = 0L;
    code_ = awt.proto.enums.Code.OK;
    commands_ = java.util.Collections.emptyList();
    player_ = awt.proto.Player.getDefaultInstance();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    if (!hasHeader()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasTimeStamp()) {
      memoizedIsInitialized = 0;
      return false;
    }
    for (int i = 0; i < getElementsCount(); i++) {
      if (!getElements(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    for (int i = 0; i < getCommandsCount(); i++) {
      if (!getCommands(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    if (hasPlayer()) {
      if (!getPlayer().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeEnum(1, header_.getNumber());
    }
    for (int i = 0; i < elements_.size(); i++) {
      output.writeMessage(2, elements_.get(i));
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeInt64(3, timeStamp_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeEnum(4, code_.getNumber());
    }
    for (int i = 0; i < commands_.size(); i++) {
      output.writeMessage(5, commands_.get(i));
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeMessage(6, player_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, header_.getNumber());
    }
    for (int i = 0; i < elements_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, elements_.get(i));
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, timeStamp_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, code_.getNumber());
    }
    for (int i = 0; i < commands_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, commands_.get(i));
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, player_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static awt.proto.Msg parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static awt.proto.Msg parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static awt.proto.Msg parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static awt.proto.Msg parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static awt.proto.Msg parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static awt.proto.Msg parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static awt.proto.Msg parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static awt.proto.Msg parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static awt.proto.Msg parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static awt.proto.Msg parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(awt.proto.Msg prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Msg}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements awt.proto.MsgOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return awt.proto.MsgProto.internal_static_Msg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return awt.proto.MsgProto.internal_static_Msg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              awt.proto.Msg.class, awt.proto.Msg.Builder.class);
    }

    // Construct using awt.proto.Msg.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getElementsFieldBuilder();
        getCommandsFieldBuilder();
        getPlayerFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      header_ = awt.proto.enums.MsgAction.LOGIN;
      bitField0_ = (bitField0_ & ~0x00000001);
      if (elementsBuilder_ == null) {
        elements_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        elementsBuilder_.clear();
      }
      timeStamp_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000004);
      code_ = awt.proto.enums.Code.OK;
      bitField0_ = (bitField0_ & ~0x00000008);
      if (commandsBuilder_ == null) {
        commands_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
      } else {
        commandsBuilder_.clear();
      }
      if (playerBuilder_ == null) {
        player_ = awt.proto.Player.getDefaultInstance();
      } else {
        playerBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000020);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return awt.proto.MsgProto.internal_static_Msg_descriptor;
    }

    public awt.proto.Msg getDefaultInstanceForType() {
      return awt.proto.Msg.getDefaultInstance();
    }

    public awt.proto.Msg build() {
      awt.proto.Msg result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public awt.proto.Msg buildPartial() {
      awt.proto.Msg result = new awt.proto.Msg(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.header_ = header_;
      if (elementsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          elements_ = java.util.Collections.unmodifiableList(elements_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.elements_ = elements_;
      } else {
        result.elements_ = elementsBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000002;
      }
      result.timeStamp_ = timeStamp_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000004;
      }
      result.code_ = code_;
      if (commandsBuilder_ == null) {
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          commands_ = java.util.Collections.unmodifiableList(commands_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.commands_ = commands_;
      } else {
        result.commands_ = commandsBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
        to_bitField0_ |= 0x00000008;
      }
      if (playerBuilder_ == null) {
        result.player_ = player_;
      } else {
        result.player_ = playerBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof awt.proto.Msg) {
        return mergeFrom((awt.proto.Msg)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(awt.proto.Msg other) {
      if (other == awt.proto.Msg.getDefaultInstance()) return this;
      if (other.hasHeader()) {
        setHeader(other.getHeader());
      }
      if (elementsBuilder_ == null) {
        if (!other.elements_.isEmpty()) {
          if (elements_.isEmpty()) {
            elements_ = other.elements_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureElementsIsMutable();
            elements_.addAll(other.elements_);
          }
          onChanged();
        }
      } else {
        if (!other.elements_.isEmpty()) {
          if (elementsBuilder_.isEmpty()) {
            elementsBuilder_.dispose();
            elementsBuilder_ = null;
            elements_ = other.elements_;
            bitField0_ = (bitField0_ & ~0x00000002);
            elementsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getElementsFieldBuilder() : null;
          } else {
            elementsBuilder_.addAllMessages(other.elements_);
          }
        }
      }
      if (other.hasTimeStamp()) {
        setTimeStamp(other.getTimeStamp());
      }
      if (other.hasCode()) {
        setCode(other.getCode());
      }
      if (commandsBuilder_ == null) {
        if (!other.commands_.isEmpty()) {
          if (commands_.isEmpty()) {
            commands_ = other.commands_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureCommandsIsMutable();
            commands_.addAll(other.commands_);
          }
          onChanged();
        }
      } else {
        if (!other.commands_.isEmpty()) {
          if (commandsBuilder_.isEmpty()) {
            commandsBuilder_.dispose();
            commandsBuilder_ = null;
            commands_ = other.commands_;
            bitField0_ = (bitField0_ & ~0x00000010);
            commandsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getCommandsFieldBuilder() : null;
          } else {
            commandsBuilder_.addAllMessages(other.commands_);
          }
        }
      }
      if (other.hasPlayer()) {
        mergePlayer(other.getPlayer());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasHeader()) {
        
        return false;
      }
      if (!hasTimeStamp()) {
        
        return false;
      }
      for (int i = 0; i < getElementsCount(); i++) {
        if (!getElements(i).isInitialized()) {
          
          return false;
        }
      }
      for (int i = 0; i < getCommandsCount(); i++) {
        if (!getCommands(i).isInitialized()) {
          
          return false;
        }
      }
      if (hasPlayer()) {
        if (!getPlayer().isInitialized()) {
          
          return false;
        }
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      awt.proto.Msg parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (awt.proto.Msg) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // required .MsgAction header = 1;
    private awt.proto.enums.MsgAction header_ = awt.proto.enums.MsgAction.LOGIN;
    /**
     * <code>required .MsgAction header = 1;</code>
     *
     * <pre>
     *自身属性
     * </pre>
     */
    public boolean hasHeader() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .MsgAction header = 1;</code>
     *
     * <pre>
     *自身属性
     * </pre>
     */
    public awt.proto.enums.MsgAction getHeader() {
      return header_;
    }
    /**
     * <code>required .MsgAction header = 1;</code>
     *
     * <pre>
     *自身属性
     * </pre>
     */
    public Builder setHeader(awt.proto.enums.MsgAction value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      header_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required .MsgAction header = 1;</code>
     *
     * <pre>
     *自身属性
     * </pre>
     */
    public Builder clearHeader() {
      bitField0_ = (bitField0_ & ~0x00000001);
      header_ = awt.proto.enums.MsgAction.LOGIN;
      onChanged();
      return this;
    }

    // repeated .Element elements = 2;
    private java.util.List<awt.proto.Element> elements_ =
      java.util.Collections.emptyList();
    private void ensureElementsIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        elements_ = new java.util.ArrayList<awt.proto.Element>(elements_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        awt.proto.Element, awt.proto.Element.Builder, awt.proto.ElementOrBuilder> elementsBuilder_;

    /**
     * <code>repeated .Element elements = 2;</code>
     */
    public java.util.List<awt.proto.Element> getElementsList() {
      if (elementsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(elements_);
      } else {
        return elementsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Element elements = 2;</code>
     */
    public int getElementsCount() {
      if (elementsBuilder_ == null) {
        return elements_.size();
      } else {
        return elementsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Element elements = 2;</code>
     */
    public awt.proto.Element getElements(int index) {
      if (elementsBuilder_ == null) {
        return elements_.get(index);
      } else {
        return elementsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Element elements = 2;</code>
     */
    public Builder setElements(
        int index, awt.proto.Element value) {
      if (elementsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureElementsIsMutable();
        elements_.set(index, value);
        onChanged();
      } else {
        elementsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Element elements = 2;</code>
     */
    public Builder setElements(
        int index, awt.proto.Element.Builder builderForValue) {
      if (elementsBuilder_ == null) {
        ensureElementsIsMutable();
        elements_.set(index, builderForValue.build());
        onChanged();
      } else {
        elementsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Element elements = 2;</code>
     */
    public Builder addElements(awt.proto.Element value) {
      if (elementsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureElementsIsMutable();
        elements_.add(value);
        onChanged();
      } else {
        elementsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Element elements = 2;</code>
     */
    public Builder addElements(
        int index, awt.proto.Element value) {
      if (elementsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureElementsIsMutable();
        elements_.add(index, value);
        onChanged();
      } else {
        elementsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Element elements = 2;</code>
     */
    public Builder addElements(
        awt.proto.Element.Builder builderForValue) {
      if (elementsBuilder_ == null) {
        ensureElementsIsMutable();
        elements_.add(builderForValue.build());
        onChanged();
      } else {
        elementsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Element elements = 2;</code>
     */
    public Builder addElements(
        int index, awt.proto.Element.Builder builderForValue) {
      if (elementsBuilder_ == null) {
        ensureElementsIsMutable();
        elements_.add(index, builderForValue.build());
        onChanged();
      } else {
        elementsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Element elements = 2;</code>
     */
    public Builder addAllElements(
        java.lang.Iterable<? extends awt.proto.Element> values) {
      if (elementsBuilder_ == null) {
        ensureElementsIsMutable();
        super.addAll(values, elements_);
        onChanged();
      } else {
        elementsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Element elements = 2;</code>
     */
    public Builder clearElements() {
      if (elementsBuilder_ == null) {
        elements_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        elementsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Element elements = 2;</code>
     */
    public Builder removeElements(int index) {
      if (elementsBuilder_ == null) {
        ensureElementsIsMutable();
        elements_.remove(index);
        onChanged();
      } else {
        elementsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Element elements = 2;</code>
     */
    public awt.proto.Element.Builder getElementsBuilder(
        int index) {
      return getElementsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Element elements = 2;</code>
     */
    public awt.proto.ElementOrBuilder getElementsOrBuilder(
        int index) {
      if (elementsBuilder_ == null) {
        return elements_.get(index);  } else {
        return elementsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Element elements = 2;</code>
     */
    public java.util.List<? extends awt.proto.ElementOrBuilder> 
         getElementsOrBuilderList() {
      if (elementsBuilder_ != null) {
        return elementsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(elements_);
      }
    }
    /**
     * <code>repeated .Element elements = 2;</code>
     */
    public awt.proto.Element.Builder addElementsBuilder() {
      return getElementsFieldBuilder().addBuilder(
          awt.proto.Element.getDefaultInstance());
    }
    /**
     * <code>repeated .Element elements = 2;</code>
     */
    public awt.proto.Element.Builder addElementsBuilder(
        int index) {
      return getElementsFieldBuilder().addBuilder(
          index, awt.proto.Element.getDefaultInstance());
    }
    /**
     * <code>repeated .Element elements = 2;</code>
     */
    public java.util.List<awt.proto.Element.Builder> 
         getElementsBuilderList() {
      return getElementsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        awt.proto.Element, awt.proto.Element.Builder, awt.proto.ElementOrBuilder> 
        getElementsFieldBuilder() {
      if (elementsBuilder_ == null) {
        elementsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            awt.proto.Element, awt.proto.Element.Builder, awt.proto.ElementOrBuilder>(
                elements_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        elements_ = null;
      }
      return elementsBuilder_;
    }

    // required int64 timeStamp = 3;
    private long timeStamp_ ;
    /**
     * <code>required int64 timeStamp = 3;</code>
     */
    public boolean hasTimeStamp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 timeStamp = 3;</code>
     */
    public long getTimeStamp() {
      return timeStamp_;
    }
    /**
     * <code>required int64 timeStamp = 3;</code>
     */
    public Builder setTimeStamp(long value) {
      bitField0_ |= 0x00000004;
      timeStamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int64 timeStamp = 3;</code>
     */
    public Builder clearTimeStamp() {
      bitField0_ = (bitField0_ & ~0x00000004);
      timeStamp_ = 0L;
      onChanged();
      return this;
    }

    // optional .Code code = 4;
    private awt.proto.enums.Code code_ = awt.proto.enums.Code.OK;
    /**
     * <code>optional .Code code = 4;</code>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .Code code = 4;</code>
     */
    public awt.proto.enums.Code getCode() {
      return code_;
    }
    /**
     * <code>optional .Code code = 4;</code>
     */
    public Builder setCode(awt.proto.enums.Code value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000008;
      code_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .Code code = 4;</code>
     */
    public Builder clearCode() {
      bitField0_ = (bitField0_ & ~0x00000008);
      code_ = awt.proto.enums.Code.OK;
      onChanged();
      return this;
    }

    // repeated .Command commands = 5;
    private java.util.List<awt.proto.command.Command> commands_ =
      java.util.Collections.emptyList();
    private void ensureCommandsIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        commands_ = new java.util.ArrayList<awt.proto.command.Command>(commands_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        awt.proto.command.Command, awt.proto.command.Command.Builder, awt.proto.command.CommandOrBuilder> commandsBuilder_;

    /**
     * <code>repeated .Command commands = 5;</code>
     */
    public java.util.List<awt.proto.command.Command> getCommandsList() {
      if (commandsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(commands_);
      } else {
        return commandsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Command commands = 5;</code>
     */
    public int getCommandsCount() {
      if (commandsBuilder_ == null) {
        return commands_.size();
      } else {
        return commandsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Command commands = 5;</code>
     */
    public awt.proto.command.Command getCommands(int index) {
      if (commandsBuilder_ == null) {
        return commands_.get(index);
      } else {
        return commandsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Command commands = 5;</code>
     */
    public Builder setCommands(
        int index, awt.proto.command.Command value) {
      if (commandsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCommandsIsMutable();
        commands_.set(index, value);
        onChanged();
      } else {
        commandsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Command commands = 5;</code>
     */
    public Builder setCommands(
        int index, awt.proto.command.Command.Builder builderForValue) {
      if (commandsBuilder_ == null) {
        ensureCommandsIsMutable();
        commands_.set(index, builderForValue.build());
        onChanged();
      } else {
        commandsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Command commands = 5;</code>
     */
    public Builder addCommands(awt.proto.command.Command value) {
      if (commandsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCommandsIsMutable();
        commands_.add(value);
        onChanged();
      } else {
        commandsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Command commands = 5;</code>
     */
    public Builder addCommands(
        int index, awt.proto.command.Command value) {
      if (commandsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCommandsIsMutable();
        commands_.add(index, value);
        onChanged();
      } else {
        commandsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Command commands = 5;</code>
     */
    public Builder addCommands(
        awt.proto.command.Command.Builder builderForValue) {
      if (commandsBuilder_ == null) {
        ensureCommandsIsMutable();
        commands_.add(builderForValue.build());
        onChanged();
      } else {
        commandsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Command commands = 5;</code>
     */
    public Builder addCommands(
        int index, awt.proto.command.Command.Builder builderForValue) {
      if (commandsBuilder_ == null) {
        ensureCommandsIsMutable();
        commands_.add(index, builderForValue.build());
        onChanged();
      } else {
        commandsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Command commands = 5;</code>
     */
    public Builder addAllCommands(
        java.lang.Iterable<? extends awt.proto.command.Command> values) {
      if (commandsBuilder_ == null) {
        ensureCommandsIsMutable();
        super.addAll(values, commands_);
        onChanged();
      } else {
        commandsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Command commands = 5;</code>
     */
    public Builder clearCommands() {
      if (commandsBuilder_ == null) {
        commands_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        commandsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Command commands = 5;</code>
     */
    public Builder removeCommands(int index) {
      if (commandsBuilder_ == null) {
        ensureCommandsIsMutable();
        commands_.remove(index);
        onChanged();
      } else {
        commandsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Command commands = 5;</code>
     */
    public awt.proto.command.Command.Builder getCommandsBuilder(
        int index) {
      return getCommandsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Command commands = 5;</code>
     */
    public awt.proto.command.CommandOrBuilder getCommandsOrBuilder(
        int index) {
      if (commandsBuilder_ == null) {
        return commands_.get(index);  } else {
        return commandsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Command commands = 5;</code>
     */
    public java.util.List<? extends awt.proto.command.CommandOrBuilder> 
         getCommandsOrBuilderList() {
      if (commandsBuilder_ != null) {
        return commandsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(commands_);
      }
    }
    /**
     * <code>repeated .Command commands = 5;</code>
     */
    public awt.proto.command.Command.Builder addCommandsBuilder() {
      return getCommandsFieldBuilder().addBuilder(
          awt.proto.command.Command.getDefaultInstance());
    }
    /**
     * <code>repeated .Command commands = 5;</code>
     */
    public awt.proto.command.Command.Builder addCommandsBuilder(
        int index) {
      return getCommandsFieldBuilder().addBuilder(
          index, awt.proto.command.Command.getDefaultInstance());
    }
    /**
     * <code>repeated .Command commands = 5;</code>
     */
    public java.util.List<awt.proto.command.Command.Builder> 
         getCommandsBuilderList() {
      return getCommandsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        awt.proto.command.Command, awt.proto.command.Command.Builder, awt.proto.command.CommandOrBuilder> 
        getCommandsFieldBuilder() {
      if (commandsBuilder_ == null) {
        commandsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            awt.proto.command.Command, awt.proto.command.Command.Builder, awt.proto.command.CommandOrBuilder>(
                commands_,
                ((bitField0_ & 0x00000010) == 0x00000010),
                getParentForChildren(),
                isClean());
        commands_ = null;
      }
      return commandsBuilder_;
    }

    // optional .Player player = 6;
    private awt.proto.Player player_ = awt.proto.Player.getDefaultInstance();
    private com.google.protobuf.SingleFieldBuilder<
        awt.proto.Player, awt.proto.Player.Builder, awt.proto.PlayerOrBuilder> playerBuilder_;
    /**
     * <code>optional .Player player = 6;</code>
     */
    public boolean hasPlayer() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional .Player player = 6;</code>
     */
    public awt.proto.Player getPlayer() {
      if (playerBuilder_ == null) {
        return player_;
      } else {
        return playerBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .Player player = 6;</code>
     */
    public Builder setPlayer(awt.proto.Player value) {
      if (playerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        player_ = value;
        onChanged();
      } else {
        playerBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      return this;
    }
    /**
     * <code>optional .Player player = 6;</code>
     */
    public Builder setPlayer(
        awt.proto.Player.Builder builderForValue) {
      if (playerBuilder_ == null) {
        player_ = builderForValue.build();
        onChanged();
      } else {
        playerBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      return this;
    }
    /**
     * <code>optional .Player player = 6;</code>
     */
    public Builder mergePlayer(awt.proto.Player value) {
      if (playerBuilder_ == null) {
        if (((bitField0_ & 0x00000020) == 0x00000020) &&
            player_ != awt.proto.Player.getDefaultInstance()) {
          player_ =
            awt.proto.Player.newBuilder(player_).mergeFrom(value).buildPartial();
        } else {
          player_ = value;
        }
        onChanged();
      } else {
        playerBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000020;
      return this;
    }
    /**
     * <code>optional .Player player = 6;</code>
     */
    public Builder clearPlayer() {
      if (playerBuilder_ == null) {
        player_ = awt.proto.Player.getDefaultInstance();
        onChanged();
      } else {
        playerBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000020);
      return this;
    }
    /**
     * <code>optional .Player player = 6;</code>
     */
    public awt.proto.Player.Builder getPlayerBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getPlayerFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .Player player = 6;</code>
     */
    public awt.proto.PlayerOrBuilder getPlayerOrBuilder() {
      if (playerBuilder_ != null) {
        return playerBuilder_.getMessageOrBuilder();
      } else {
        return player_;
      }
    }
    /**
     * <code>optional .Player player = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        awt.proto.Player, awt.proto.Player.Builder, awt.proto.PlayerOrBuilder> 
        getPlayerFieldBuilder() {
      if (playerBuilder_ == null) {
        playerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            awt.proto.Player, awt.proto.Player.Builder, awt.proto.PlayerOrBuilder>(
                player_,
                getParentForChildren(),
                isClean());
        player_ = null;
      }
      return playerBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:Msg)
  }

  static {
    defaultInstance = new Msg(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:Msg)
}

