// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

package awt.proto;

public final class MsgProto {
  private MsgProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_Msg_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Msg_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_Player_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Player_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tmsg.proto\032\relement.proto\032\rCommand.prot" +
      "o\032\013enums.proto\"\232\001\n\003Msg\022\032\n\006header\030\001 \002(\0162\n" +
      ".MsgAction\022\032\n\010elements\030\002 \003(\0132\010.Element\022\021" +
      "\n\ttimeStamp\030\003 \002(\003\022\023\n\004code\030\004 \001(\0162\005.Code\022\032" +
      "\n\010commands\030\005 \003(\0132\010.Command\022\027\n\006player\030\006 \001" +
      "(\0132\007.Player\".\n\006Player\022\n\n\002ip\030\001 \001(\t\022\014\n\004nam" +
      "e\030\002 \002(\t\022\n\n\002id\030\003 \001(\005B\027\n\tawt.protoB\010MsgPro" +
      "toP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Msg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Msg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Msg_descriptor,
              new java.lang.String[] { "Header", "Elements", "TimeStamp", "Code", "Commands", "Player", });
          internal_static_Player_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Player_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Player_descriptor,
              new java.lang.String[] { "Ip", "Name", "Id", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          awt.proto.ElementProto.getDescriptor(),
          awt.proto.command.CommandProto.getDescriptor(),
          awt.proto.enums.Enums.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
