// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

package awt.proto;

public interface PlayerOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional string ip = 1;
  /**
   * <code>optional string ip = 1;</code>
   *
   * <pre>
   *ip
   * </pre>
   */
  boolean hasIp();
  /**
   * <code>optional string ip = 1;</code>
   *
   * <pre>
   *ip
   * </pre>
   */
  java.lang.String getIp();
  /**
   * <code>optional string ip = 1;</code>
   *
   * <pre>
   *ip
   * </pre>
   */
  com.google.protobuf.ByteString
      getIpBytes();

  // required string name = 2;
  /**
   * <code>required string name = 2;</code>
   *
   * <pre>
   *昵称
   * </pre>
   */
  boolean hasName();
  /**
   * <code>required string name = 2;</code>
   *
   * <pre>
   *昵称
   * </pre>
   */
  java.lang.String getName();
  /**
   * <code>required string name = 2;</code>
   *
   * <pre>
   *昵称
   * </pre>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  // optional int32 id = 3;
  /**
   * <code>optional int32 id = 3;</code>
   *
   * <pre>
   *玩家id
   * </pre>
   */
  boolean hasId();
  /**
   * <code>optional int32 id = 3;</code>
   *
   * <pre>
   *玩家id
   * </pre>
   */
  int getId();
}
