// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Command.proto

package awt.proto.command;

public final class CommandProto {
  private CommandProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_Command_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Command_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rCommand.proto\032\relement.proto\032\013enums.pr" +
      "oto\"\313\002\n\007Command\022!\n\013commandType\030\001 \002(\0162\014.C" +
      "ommandType\022\021\n\telementId\030\002 \001(\005\022\026\n\016startTi" +
      "mestamp\030\003 \002(\003\022\024\n\014endTimestamp\030\004 \002(\003\022\r\n\005c" +
      "ount\030\005 \002(\005\022\021\n\tneedCount\030\006 \002(\005\022\027\n\006status\030" +
      "\007 \002(\0162\007.Status\022%\n\relementAction\030\010 \001(\0162\016." +
      "ElementAction\022\037\n\ntankAction\030\t \001(\0162\013.Tank" +
      "Action\022\027\n\006direct\030\n \001(\0162\007.Direct\022\017\n\007newDa" +
      "ta\030\013 \001(\005\022\035\n\tmsgAction\030\014 \001(\0162\n.MsgAction\022" +
      "\020\n\010playerId\030\r \001(\005B#\n\021awt.proto.commandB\014",
      "CommandProtoP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Command_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Command_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Command_descriptor,
              new java.lang.String[] { "CommandType", "ElementId", "StartTimestamp", "EndTimestamp", "Count", "NeedCount", "Status", "ElementAction", "TankAction", "Direct", "NewData", "MsgAction", "PlayerId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          awt.proto.ElementProto.getDescriptor(),
          awt.proto.enums.Enums.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
