// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Command.proto

package awt.proto.command;

public interface CommandOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // required .CommandType commandType = 1;
  /**
   * <code>required .CommandType commandType = 1;</code>
   *
   * <pre>
   *元素id
   * </pre>
   */
  boolean hasCommandType();
  /**
   * <code>required .CommandType commandType = 1;</code>
   *
   * <pre>
   *元素id
   * </pre>
   */
  awt.proto.enums.CommandType getCommandType();

  // optional int32 elementId = 2;
  /**
   * <code>optional int32 elementId = 2;</code>
   *
   * <pre>
   *元素id
   * </pre>
   */
  boolean hasElementId();
  /**
   * <code>optional int32 elementId = 2;</code>
   *
   * <pre>
   *元素id
   * </pre>
   */
  int getElementId();

  // required int64 startTimestamp = 3;
  /**
   * <code>required int64 startTimestamp = 3;</code>
   *
   * <pre>
   *事件戳
   * </pre>
   */
  boolean hasStartTimestamp();
  /**
   * <code>required int64 startTimestamp = 3;</code>
   *
   * <pre>
   *事件戳
   * </pre>
   */
  long getStartTimestamp();

  // required int64 endTimestamp = 4;
  /**
   * <code>required int64 endTimestamp = 4;</code>
   *
   * <pre>
   *事件戳
   * </pre>
   */
  boolean hasEndTimestamp();
  /**
   * <code>required int64 endTimestamp = 4;</code>
   *
   * <pre>
   *事件戳
   * </pre>
   */
  long getEndTimestamp();

  // required int32 count = 5;
  /**
   * <code>required int32 count = 5;</code>
   *
   * <pre>
   *指令计数器
   * </pre>
   */
  boolean hasCount();
  /**
   * <code>required int32 count = 5;</code>
   *
   * <pre>
   *指令计数器
   * </pre>
   */
  int getCount();

  // required int32 needCount = 6;
  /**
   * <code>required int32 needCount = 6;</code>
   *
   * <pre>
   *需要执行的次数
   * </pre>
   */
  boolean hasNeedCount();
  /**
   * <code>required int32 needCount = 6;</code>
   *
   * <pre>
   *需要执行的次数
   * </pre>
   */
  int getNeedCount();

  // required .Status status = 7;
  /**
   * <code>required .Status status = 7;</code>
   */
  boolean hasStatus();
  /**
   * <code>required .Status status = 7;</code>
   */
  awt.proto.enums.Status getStatus();

  // optional .ElementAction elementAction = 8;
  /**
   * <code>optional .ElementAction elementAction = 8;</code>
   */
  boolean hasElementAction();
  /**
   * <code>optional .ElementAction elementAction = 8;</code>
   */
  awt.proto.enums.ElementAction getElementAction();

  // optional .TankAction tankAction = 9;
  /**
   * <code>optional .TankAction tankAction = 9;</code>
   */
  boolean hasTankAction();
  /**
   * <code>optional .TankAction tankAction = 9;</code>
   */
  awt.proto.enums.TankAction getTankAction();

  // optional .Direct direct = 10;
  /**
   * <code>optional .Direct direct = 10;</code>
   */
  boolean hasDirect();
  /**
   * <code>optional .Direct direct = 10;</code>
   */
  awt.proto.enums.Direct getDirect();

  // optional int32 newData = 11;
  /**
   * <code>optional int32 newData = 11;</code>
   */
  boolean hasNewData();
  /**
   * <code>optional int32 newData = 11;</code>
   */
  int getNewData();

  // optional .MsgAction msgAction = 12;
  /**
   * <code>optional .MsgAction msgAction = 12;</code>
   */
  boolean hasMsgAction();
  /**
   * <code>optional .MsgAction msgAction = 12;</code>
   */
  awt.proto.enums.MsgAction getMsgAction();

  // optional int32 playerId = 13;
  /**
   * <code>optional int32 playerId = 13;</code>
   */
  boolean hasPlayerId();
  /**
   * <code>optional int32 playerId = 13;</code>
   */
  int getPlayerId();
}
